// Card database: the starter decks ST01-ST14 (plus the ST09 Ultimate Deck extras).
// Stats and text sourced from the official card list (via the gcg-api dataset).
// Card names, text and Gundam are property of Bandai; this is metadata only.

import type { CardDef, Color, TokenDef } from './types';

export const CARDS: Record<string, CardDef> = {
  // ---------- ST01 Heroic Beginnings (Blue / White) ----------
  'ST01-001': {
    id: 'ST01-001', name: 'Gundam', type: 'UNIT', color: 'Blue', level: 4, cost: 3, ap: 3, hp: 4,
    traits: ['Earth Federation', 'White Base Team'], link: ['Amuro Ray'], zones: ['Space', 'Earth'],
    text: '<Repair 2> (At the end of your turn, this Unit recovers the specified number of HP.)\n【During Pair】During your turn, all your Units get AP+1.',
    keywords: { repair: 2 },
    tip: 'Your flagship. Pair Amuro to make it a Link Unit that attacks the turn it lands, and the team-wide AP+1 turns every trade in your favor.',
  },
  'ST01-002': {
    id: 'ST01-002', name: 'Gundam (MA Form)', type: 'UNIT', color: 'Blue', level: 5, cost: 3, ap: 4, hp: 3,
    traits: ['Earth Federation', 'White Base Team'], link: ['Amuro Ray'], zones: ['Space'],
    text: '【When Paired･(White Base Team) Pilot】Draw 1.',
    tip: 'High AP, low HP. Pairing any White Base Team pilot (Amuro, Kai, Hayato) refunds a card.',
  },
  'ST01-003': {
    id: 'ST01-003', name: 'Guncannon', type: 'UNIT', color: 'Blue', level: 3, cost: 2, ap: 2, hp: 4,
    traits: ['Earth Federation', 'White Base Team'], link: ['Kai Shiden'], zones: ['Space', 'Earth'],
    text: '-',
    tip: 'A sturdy early body. 4 HP survives most early attackers. "Kai\'s Resolve" can be paired as Kai Shiden to link it.',
  },
  'ST01-004': {
    id: 'ST01-004', name: 'Guntank', type: 'UNIT', color: 'Blue', level: 3, cost: 2, ap: 2, hp: 3,
    traits: ['Earth Federation', 'White Base Team'], link: ['Hayato Kobayashi'], zones: ['Space', 'Earth'],
    text: '【Deploy】Choose 1 enemy Unit with 2 or less HP. Rest it.',
    tip: 'Resting an enemy unit lets your other units attack it this turn. Deploy it before you attack, not after.',
  },
  'ST01-005': {
    id: 'ST01-005', name: 'GM', type: 'UNIT', color: 'Blue', level: 2, cost: 1, ap: 2, hp: 2,
    traits: ['Earth Federation'], zones: ['Space', 'Earth'],
    text: '-',
    tip: 'Cheap pressure. A turn-1 or turn-2 GM starts chipping shields before the opponent stabilizes.',
  },
  'ST01-006': {
    id: 'ST01-006', name: 'Gundam Aerial (Permet Score Six)', type: 'UNIT', color: 'White', level: 5, cost: 4, ap: 4, hp: 4,
    traits: ['Academy'], link: ['Suletta Mercury'], zones: ['Space', 'Earth'],
    text: '【When Paired】Choose 1 enemy Unit that is Lv.5 or lower. It gets AP-3 during this turn.',
    tip: 'Pair Suletta and shrink an enemy unit to 0-1 AP, then attack it for a free kill.',
  },
  'ST01-007': {
    id: 'ST01-007', name: 'Gundam Aerial (Bit on Form)', type: 'UNIT', color: 'White', level: 4, cost: 2, ap: 3, hp: 4,
    traits: ['Academy'], link: ['Suletta Mercury'], zones: ['Space', 'Earth'],
    text: '-',
    tip: 'Best stats-per-cost in the deck: 3/4 for 2. Play it on curve at Lv.4.',
  },
  'ST01-008': {
    id: 'ST01-008', name: 'Demi Trainer', type: 'UNIT', color: 'White', level: 1, cost: 1, ap: 1, hp: 1,
    traits: ['Academy'], zones: ['Space', 'Earth'],
    text: '<Blocker> (Rest this Unit to change the attack target to it.)',
    keywords: { blocker: true },
    tip: 'A 1-cost shield. Block a big attack to save a Shield card or a valuable unit.',
  },
  'ST01-009': {
    id: 'ST01-009', name: 'Zowort', type: 'UNIT', color: 'White', level: 2, cost: 2, ap: 3, hp: 2,
    traits: ['Academy'], zones: ['Space', 'Earth'],
    text: "<Blocker> (Rest this Unit to change the attack target to it.)\nThis Unit can't choose the enemy player as its attack target.",
    keywords: { blocker: true },
    tip: 'Defensive: it can only attack rested enemy units, but 3 AP blocks and kills most early attackers.',
  },
  'ST01-010': {
    id: 'ST01-010', name: 'Amuro Ray', type: 'PILOT', color: 'Blue', level: 4, cost: 1, ap: 2, hp: 1,
    traits: ['Earth Federation', 'White Base Team', 'Newtype'],
    text: '【Burst】Add this card to your hand.\n【When Paired】Choose 1 enemy Unit with 5 or less HP. Rest it.',
    tip: 'Pair onto Gundam for a Link Unit. The When Paired rest lets you attack the target the same turn.',
  },
  'ST01-011': {
    id: 'ST01-011', name: 'Suletta Mercury', type: 'PILOT', color: 'White', level: 4, cost: 1, ap: 1, hp: 2,
    traits: ['Academy'],
    text: '【Burst】Add this card to your hand.\n【Attack】【Once per Turn】Choose 1 of your Resources. Set it as active.',
    tip: 'Every attack refunds a resource. Attack first, then spend the reactivated resource on more plays.',
  },
  'ST01-012': {
    id: 'ST01-012', name: 'Thoroughly Damaged', type: 'COMMAND', color: 'Blue', level: 2, cost: 1, ap: 0, hp: 1,
    traits: ['Earth Federation', 'White Base Team'], timing: ['Main'], pilotName: 'Hayato Kobayashi',
    text: '【Main】Choose 1 rested enemy Unit. Deal 1 damage to it.\n【Pilot】[Hayato Kobayashi]',
    tip: 'Finish off a damaged rested unit, or pair it as Hayato to link a Guntank.',
  },
  'ST01-013': {
    id: 'ST01-013', name: "Kai's Resolve", type: 'COMMAND', color: 'Blue', level: 3, cost: 1, ap: 1, hp: 0,
    traits: ['Earth Federation', 'White Base Team'], timing: ['Main'], pilotName: 'Kai Shiden',
    text: '【Main】Choose 1 friendly Unit. It recovers 3 HP.\n【Pilot】[Kai Shiden]',
    tip: 'Heal a damaged Gundam, or pair it as Kai Shiden to link a Guncannon.',
  },
  'ST01-014': {
    id: 'ST01-014', name: 'Unforeseen Incident', type: 'COMMAND', color: 'White', level: 3, cost: 1,
    traits: [], timing: ['Main', 'Action'],
    text: "【Burst】Activate this card's 【Main】.\n【Main】/【Action】Choose 1 enemy Unit. It gets AP-3 during this turn.",
    tip: 'Playable during battle (Action). Shrink the attacker so your blocker or defender survives, or neuter a shield hit.',
  },
  'ST01-015': {
    id: 'ST01-015', name: 'White Base', type: 'BASE', color: 'Blue', level: 3, cost: 2, ap: 0, hp: 5,
    traits: ['Earth Federation', 'White Base Team', 'Warship'], zones: ['Space', 'Earth'],
    text: '【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand.\n【Activate･Main】【Once per Turn】②：Deploy 1 [Gundam]((White Base Team)･AP3･HP3) Unit token if you have no Units in play, deploy 1 [Guncannon]((White Base Team)･AP2･HP2) Unit token if you have only 1 Unit in play, or deploy 1 [Guntank]((White Base Team)･AP1･HP1) Unit token if you have 2 or more Units in play.',
    tip: 'A 5 HP wall that also draws you a card (from your shields) and makes tokens. Best when your board is empty.',
  },
  'ST01-016': {
    id: 'ST01-016', name: 'Asticassia School of Technology, Earth House', type: 'BASE', color: 'White', level: 2, cost: 1, ap: 0, hp: 5,
    traits: ['Academy', 'Stronghold'], zones: ['Space'],
    text: '【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand.\n【Activate･Main】Rest this Base：All friendly Link Units get AP+1 during this turn.',
    tip: 'Cheap protection plus a card. Rest it before attacking with Link Units for extra damage.',
  },

  // ---------- ST02 Wings of Advance (Green / Blue) ----------
  'ST02-001': {
    id: 'ST02-001', name: 'Wing Gundam', type: 'UNIT', color: 'Green', level: 6, cost: 4, ap: 4, hp: 5,
    traits: ['Operation Meteor'], link: ['Heero Yuy'], zones: ['Space', 'Earth'],
    text: "<Breach 5> (When this Unit's attack destroys an enemy Unit, deal the specified amount of damage to the first card in that opponent's shield area.)\nThis Unit may choose an active enemy Unit that is Lv.4 or lower as its attack target.",
    keywords: { breach: 5 },
    tip: 'Kill a unit and Breach 5 wipes their Base or a Shield too. It can even attack active low-level units.',
  },
  'ST02-002': {
    id: 'ST02-002', name: 'Wing Gundam (Bird Mode)', type: 'UNIT', color: 'Green', level: 3, cost: 3, ap: 2, hp: 2,
    traits: ['Operation Meteor'], link: ['Heero Yuy'], zones: ['Space', 'Earth'],
    text: '【Deploy】Place 1 EX Resource.',
    tip: 'Ramp. The EX Resource raises your level immediately, letting you play bigger cards a turn early.',
  },
  'ST02-003': {
    id: 'ST02-003', name: 'Gundam Heavyarms', type: 'UNIT', color: 'Green', level: 5, cost: 3, ap: 3, hp: 4,
    traits: ['Operation Meteor'], link: ['Trowa Barton'], zones: ['Earth'],
    text: '【During Pair】During your turn, when this Unit destroys an enemy Unit with battle damage, deal 1 damage to all enemy Units that are Lv.3 or lower.',
    tip: 'Paired, every kill splashes 1 damage across their small units. Pair "Simultaneous Fire" as Trowa to link it.',
  },
  'ST02-004': {
    id: 'ST02-004', name: 'Gundam Sandrock', type: 'UNIT', color: 'Green', level: 4, cost: 2, ap: 4, hp: 3,
    traits: ['Operation Meteor'], link: ['Quatre Raberba Winner'], zones: ['Earth'],
    text: '-',
    tip: '4 AP for 2 cost is a bargain. Kills almost any early unit in one hit.',
  },
  'ST02-005': {
    id: 'ST02-005', name: 'Maganac', type: 'UNIT', color: 'Green', level: 2, cost: 2, ap: 3, hp: 2,
    traits: ['Maganac Corps'], zones: ['Space', 'Earth'],
    text: '-',
    tip: 'Aggressive early drop. Trades up into 2 HP units.',
  },
  'ST02-006': {
    id: 'ST02-006', name: 'Tallgeese', type: 'UNIT', color: 'Blue', level: 5, cost: 4, ap: 4, hp: 4,
    traits: ['OZ'], link: ['Zechs Merquise'], zones: ['Space', 'Earth'],
    text: '【Activate･Main】【Once per Turn】④：Set this Unit as active.',
    tip: 'Pay 4 to untap and attack twice in one turn. Devastating late-game with spare resources.',
  },
  'ST02-007': {
    id: 'ST02-007', name: 'Leo', type: 'UNIT', color: 'Blue', level: 2, cost: 2, ap: 2, hp: 2,
    traits: ['OZ'], link: ['(OZ)'], zones: ['Space', 'Earth'],
    text: '-',
    tip: 'Links with ANY OZ-trait pilot (Zechs). A linked Leo attacks immediately.',
  },
  'ST02-008': {
    id: 'ST02-008', name: 'Aries', type: 'UNIT', color: 'Blue', level: 2, cost: 2, ap: 2, hp: 1,
    traits: ['OZ'], zones: ['Earth'],
    text: '<Blocker> (Rest this Unit to change the attack target to it.)',
    keywords: { blocker: true },
    tip: 'A blocker with 2 AP: blocking a 1 HP attacker kills it.',
  },
  'ST02-009': {
    id: 'ST02-009', name: 'Tragos', type: 'UNIT', color: 'Blue', level: 1, cost: 1, ap: 1, hp: 1,
    traits: ['OZ'], zones: ['Earth'],
    text: '<Blocker> (Rest this Unit to change the attack target to it.)',
    keywords: { blocker: true },
    tip: 'One-cost blocker. Absorbs one attack that would otherwise hit a shield.',
  },
  'ST02-010': {
    id: 'ST02-010', name: 'Heero Yuy', type: 'PILOT', color: 'Green', level: 4, cost: 1, ap: 2, hp: 1,
    traits: ['Operation Meteor'],
    text: '【Burst】Add this card to your hand.\n【During Link】This Unit gets AP+1 and HP+1.',
    tip: 'On a Wing Gundam: +3 AP / +2 HP total. A linked Wing is a 7/7 that Breaches for 5.',
  },
  'ST02-011': {
    id: 'ST02-011', name: 'Zechs Merquise', type: 'PILOT', color: 'Blue', level: 5, cost: 1, ap: 2, hp: 1,
    traits: ['OZ'],
    text: '【Burst】Add this card to your hand.\n【During Link】During your turn, when this Unit destroys an enemy Unit with battle damage, draw 1.',
    tip: 'Links with Tallgeese or Leo. Kill units to draw cards.',
  },
  'ST02-012': {
    id: 'ST02-012', name: 'Simultaneous Fire', type: 'COMMAND', color: 'Green', level: 4, cost: 1, ap: 1, hp: 1,
    traits: ['Operation Meteor'], timing: ['Main'], pilotName: 'Trowa Barton',
    text: '【Main】Choose 1 of your Units. It gains <Breach 3> during this turn.\n【Pilot】[Trowa Barton]',
    tip: 'Give Breach 3 to a unit about to kill something, or pair it as Trowa to link Heavyarms.',
  },
  'ST02-013': {
    id: 'ST02-013', name: 'Peaceful Timbre', type: 'COMMAND', color: 'Green', level: 4, cost: 1, ap: 1, hp: 1,
    traits: ['Operation Meteor'], timing: ['Action'], pilotName: 'Quatre Raberba Winner',
    text: "【Action】During this battle, your shield area cards can't receive damage from enemy Units that are Lv.4 or lower.\n【Pilot】[Quatre Raberba Winner]",
    tip: 'Play during the action step of an enemy attack to blank a shield hit, or pair it as Quatre to link Sandrock.',
  },
  'ST02-014': {
    id: 'ST02-014', name: 'Siege Ploy', type: 'COMMAND', color: 'Blue', level: 3, cost: 1,
    traits: [], timing: ['Main', 'Action'],
    text: "【Burst】Activate this card's 【Main】.\n【Main】/【Action】Choose 1 enemy Unit with 5 or less HP. Rest it.",
    tip: 'Rest a unit so you can attack it, or rest a would-be blocker before you swing.',
  },
  'ST02-015': {
    id: 'ST02-015', name: 'Saint Gabriel Institute', type: 'BASE', color: 'Green', level: 2, cost: 2, ap: 0, hp: 5,
    traits: ['Academy', 'Stronghold'], zones: ['Earth'],
    text: '【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand. Then, look at the top 2 cards of your deck and return 1 to the top and 1 to the bottom.',
    tip: 'Protection, a card, and a peek at your next draws.',
  },
  'ST02-016': {
    id: 'ST02-016', name: 'Corsica Base', type: 'BASE', color: 'Blue', level: 3, cost: 3, ap: 0, hp: 5,
    traits: ['OZ', 'Stronghold'], zones: ['Earth'],
    text: '【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand. Then, if it is your turn, deploy 1 [Tallgeese]((OZ)･AP4･HP2) Unit token. If it is your turn and a card with "Corsica Base" in its card name is in your trash, deploy 2 [Leo]((OZ)･AP1･HP1) Unit tokens instead.',
    tip: 'Deploy it on your turn for a free 4/2 Tallgeese token. From a Burst on the opponent\'s turn you only get the base and the card.',
  },

  // ---------- ST03 Zeon's Rush (Red / Green) ----------
  'ST03-001': {
    id: 'ST03-001', name: 'Sinanju', type: 'UNIT', color: 'Red', level: 6, cost: 5, ap: 5, hp: 4,
    traits: ['Neo Zeon'], link: ['Full Frontal'], zones: ['Space'],
    text: "【During Pair】This Unit gains <High-Maneuver>.\n(This Unit can't be blocked.)\nDuring your turn, when this Unit destroys an enemy shield area card with battle damage, choose 1 enemy Unit. Deal 2 damage to it.",
    tip: 'Red\'s finisher: unblockable once paired, and every Shield or Base it breaks also burns an enemy Unit for 2.',
  },
  'ST03-002': {
    id: 'ST03-002', name: "Angelo's Geara Zulu", type: 'UNIT', color: 'Red', level: 4, cost: 3, ap: 3, hp: 3,
    traits: ['Neo Zeon'], link: ['Angelo Sauper'], zones: ['Space'],
    text: '【Activate･Main】<Support 2> (Rest this Unit. 1 other friendly Unit gets AP+(specified amount) during this turn.)',
    keywords: { support: 2 },
    tip: 'Rest it to give another Unit +2 AP before an attack. Red trades a body for a kill.',
  },
  'ST03-003': {
    id: 'ST03-003', name: 'Geara Zulu', type: 'UNIT', color: 'Red', level: 3, cost: 2, ap: 3, hp: 2,
    traits: ['Neo Zeon'], link: ['(Neo Zeon)'], zones: ['Space'],
    text: '-',
    tip: 'Links with any Neo Zeon pilot (Full Frontal). 3 AP for 2 is pure aggression.',
  },
  'ST03-004': {
    id: 'ST03-004', name: 'Gaza D (Sleeves)', type: 'UNIT', color: 'Red', level: 2, cost: 2, ap: 2, hp: 1,
    traits: ['Neo Zeon'], zones: ['Space'],
    text: '【Activate･Main】<Support 2> (Rest this Unit. 1 other friendly Unit gets AP+(specified amount) during this turn.)',
    keywords: { support: 2 },
    tip: 'Fragile, so use it as a Support battery: +2 AP to your real attacker each turn.',
  },
  'ST03-005': {
    id: 'ST03-005', name: 'Dra-C (Sleeves)', type: 'UNIT', color: 'Red', level: 1, cost: 1, ap: 1, hp: 2,
    traits: ['Neo Zeon'], zones: ['Space'],
    text: '-',
    tip: 'Turn-1 body. Chips a Shield early or soaks a hit later.',
  },
  'ST03-006': {
    id: 'ST03-006', name: "Char's Zaku Ⅱ", type: 'UNIT', color: 'Green', level: 3, cost: 2, ap: 3, hp: 2,
    traits: ['Zeon'], link: ['Char Aznable'], zones: ['Space', 'Earth'],
    text: '【Destroyed】Look at the top 3 cards of your deck. You may reveal 1 (Zeon)/(Neo Zeon) Unit card among them and add it to your hand. Return the remaining cards randomly to the bottom of your deck.',
    tip: 'Green card advantage: trade it away freely, it replaces itself with a Zeon Unit.',
  },
  'ST03-007': {
    id: 'ST03-007', name: 'Zaku Ⅰ', type: 'UNIT', color: 'Green', level: 1, cost: 1, ap: 1, hp: 2,
    traits: ['Zeon'], zones: ['Space', 'Earth'],
    text: '-',
    tip: 'Cheap body for the curve.',
  },
  'ST03-008': {
    id: 'ST03-008', name: 'Zaku Ⅱ', type: 'UNIT', color: 'Green', level: 2, cost: 1, ap: 1, hp: 2,
    traits: ['Zeon'], zones: ['Space', 'Earth'],
    text: '【Attack】This Unit gets AP+2 during this turn.',
    tip: 'Attacks as a 3 AP Unit for 1 cost, but blocks and defends as a 1 AP Unit.',
  },
  'ST03-009': {
    id: 'ST03-009', name: 'Gouf', type: 'UNIT', color: 'Green', level: 3, cost: 3, ap: 2, hp: 3,
    traits: ['Zeon'], link: ['Ramba Ral'], zones: ['Earth'],
    text: '【Deploy】Deploy 1 rested [Zaku Ⅱ]((Zeon)･AP1･HP1) Unit token.',
    tip: 'Two bodies for one card. The token arrives rested, so it attacks next turn.',
  },
  'ST03-010': {
    id: 'ST03-010', name: 'Full Frontal', type: 'PILOT', color: 'Red', level: 6, cost: 1, ap: 2, hp: 2,
    traits: ['Neo Zeon', 'Cyber-Newtype'],
    text: '【Burst】Add this card to your hand.\n【When Paired】You may deploy 1 (Neo Zeon)/(Zeon) Unit card that is Lv.4 or lower from your hand.',
    tip: 'Pair him and drop a free Geara Zulu or Zaku from hand. Tempo swing.',
  },
  'ST03-011': {
    id: 'ST03-011', name: 'Char Aznable', type: 'PILOT', color: 'Green', level: 3, cost: 1, ap: 1, hp: 1,
    traits: ['Zeon', 'Newtype'],
    text: "【Burst】Add this card to your hand.\n【Attack】During this turn, this Unit gets AP+1 and, if it is a Link Unit, it gains <High-Maneuver>.\n(This Unit can't be blocked.)",
    tip: "On Char's Zaku II the attack can't be blocked: your Shield hits always connect.",
  },
  'ST03-012': {
    id: 'ST03-012', name: 'Indignation', type: 'COMMAND', color: 'Red', level: 2, cost: 1, ap: 1, hp: 0,
    traits: ['Neo Zeon'], timing: ['Main', 'Action'], pilotName: 'Angelo Sauper',
    text: '【Main】/【Action】Choose 1 friendly Unit. It gets AP+2 during this turn.\n【Pilot】[Angelo Sauper]',
    tip: 'A combat trick: +2 AP in the action step turns a losing battle into a kill.',
  },
  'ST03-013': {
    id: 'ST03-013', name: 'Close Combat', type: 'COMMAND', color: 'Red', level: 2, cost: 2,
    traits: [], timing: ['Main', 'Action'],
    text: "【Burst】Activate this card's 【Main】.\n【Main】/【Action】Choose 1 enemy Unit. Deal 2 damage to it.",
    tip: 'Direct damage: finish a damaged Unit or kill a 2 HP blocker before you attack.',
  },
  'ST03-014': {
    id: 'ST03-014', name: 'The Blue Giant', type: 'COMMAND', color: 'Green', level: 4, cost: 1, ap: 1, hp: 1,
    traits: ['Zeon'], timing: ['Action'], pilotName: 'Ramba Ral',
    text: "【Action】Choose 1 friendly Unit. It can't receive battle damage from enemy Units with 2 or less AP during this battle.\n【Pilot】[Ramba Ral]",
    tip: 'Protects a Unit from small attackers this battle, or pairs as Ramba Ral to link Gouf.',
  },
  'ST03-015': {
    id: 'ST03-015', name: 'Rewloola', type: 'BASE', color: 'Red', level: 3, cost: 2, ap: 0, hp: 5,
    traits: ['Neo Zeon', 'Warship'], zones: ['Space'],
    text: '【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand. Then, choose 1 enemy Unit with 5 or less AP. Deal 1 damage to it.',
    tip: 'A wall that also pings an enemy Unit on arrival.',
  },
  'ST03-016': {
    id: 'ST03-016', name: 'Falmel', type: 'BASE', color: 'Green', level: 3, cost: 2, ap: 0, hp: 5,
    traits: ['Zeon', 'Warship'], zones: ['Space'],
    text: "【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand. Then, if it is your turn, deploy 1 rested [Char's Zaku Ⅱ]((Zeon)･AP3･HP1) Unit token.",
    tip: 'Deploy on your turn for a free 3 AP token.',
  },

  // ---------- ST04 SEED Strike (White / Red) ----------
  'ST04-001': {
    id: 'ST04-001', name: 'Aile Strike Gundam', type: 'UNIT', color: 'White', level: 5, cost: 4, ap: 4, hp: 4,
    traits: ['Earth Alliance'], link: ['Kira Yamato'], zones: ['Space', 'Earth'],
    text: "<Blocker> (Rest this Unit to change the attack target to it.)\n【When Paired･Lv.4 or Higher Pilot】Choose 1 enemy Unit with 4 or less HP. Return it to its owner's hand.",
    keywords: { blocker: true },
    tip: 'A 4/4 Blocker that bounces an enemy Unit when Kira lands: they lose the tempo and the Pilot on it.',
  },
  'ST04-002': {
    id: 'ST04-002', name: 'Strike Gundam', type: 'UNIT', color: 'White', level: 4, cost: 2, ap: 3, hp: 3,
    traits: ['Earth Alliance'], link: ['Kira Yamato'], zones: ['Space', 'Earth'],
    text: '【Deploy】Draw 1. Then, discard 1.',
    tip: 'Filters your hand: draw first, then throw away the card you least need.',
  },
  'ST04-003': {
    id: 'ST04-003', name: 'Moebius Zero', type: 'UNIT', color: 'White', level: 3, cost: 2, ap: 2, hp: 4,
    traits: ['Earth Alliance'], link: ['Mu La Flaga'], zones: ['Space'],
    text: '-',
    tip: 'Sturdy. Links with Hawk of Endymion played as Mu La Flaga.',
  },
  'ST04-004': {
    id: 'ST04-004', name: 'Moebius', type: 'UNIT', color: 'White', level: 1, cost: 1, ap: 1, hp: 1,
    traits: ['Earth Alliance'], zones: ['Space'],
    text: '<Blocker> (Rest this Unit to change the attack target to it.)',
    keywords: { blocker: true },
    tip: 'One-cost Blocker.',
  },
  'ST04-005': {
    id: 'ST04-005', name: 'Strike Dagger', type: 'UNIT', color: 'White', level: 2, cost: 2, ap: 3, hp: 2,
    traits: ['Earth Alliance'], zones: ['Space', 'Earth'],
    text: '-',
    tip: 'Early attacker.',
  },
  'ST04-006': {
    id: 'ST04-006', name: 'Aegis Gundam', type: 'UNIT', color: 'Red', level: 4, cost: 3, ap: 4, hp: 3,
    traits: ['ZAFT'], link: ['Athrun Zala'], zones: ['Space', 'Earth'],
    text: '【Attack】If this Unit has 5 or more AP, choose 1 enemy Unit that is Lv.5 or higher. Deal 3 damage to it.',
    tip: 'With Athrun (+1 AP) it hits 5 AP and snipes a big enemy Unit for 3 every attack.',
  },
  'ST04-007': {
    id: 'ST04-007', name: 'Aegis Gundam (MA Mode)', type: 'UNIT', color: 'Red', level: 4, cost: 3, ap: 3, hp: 4,
    traits: ['ZAFT'], link: ['Athrun Zala'], zones: ['Space', 'Earth'],
    text: "<Breach 3> (When this Unit's attack destroys an enemy Unit, deal the specified amount of damage to the first card in that opponent's shield area.)",
    keywords: { breach: 3 },
    tip: 'Kill a Unit and Breach 3 hits their Base or breaks a Shield.',
  },
  'ST04-008': {
    id: 'ST04-008', name: 'Ginn', type: 'UNIT', color: 'Red', level: 2, cost: 1, ap: 2, hp: 2,
    traits: ['ZAFT'], zones: ['Space', 'Earth'],
    text: '-',
    tip: 'Efficient 2/2 for 1.',
  },
  'ST04-009': {
    id: 'ST04-009', name: "Miguel's Ginn", type: 'UNIT', color: 'Red', level: 2, cost: 2, ap: 3, hp: 1,
    traits: ['ZAFT'], link: ['Miguel Ayman'], zones: ['Space', 'Earth'],
    text: '【During Pair】【Destroyed】If you have another Link Unit in play, draw 1.',
    tip: 'Glass cannon. Paired and with another Link Unit out, dying draws you a card.',
  },
  'ST04-010': {
    id: 'ST04-010', name: 'Kira Yamato', type: 'PILOT', color: 'White', level: 4, cost: 1, ap: 2, hp: 1,
    traits: ['Earth Alliance', 'Coordinator'],
    text: '【Burst】Add this card to your hand.\n【Attack】Choose 1 enemy Unit. It gets AP-2 during this battle.',
    tip: 'Every attack shrinks the defender by 2 AP: your Unit survives trades it should lose.',
  },
  'ST04-011': {
    id: 'ST04-011', name: 'Athrun Zala', type: 'PILOT', color: 'Red', level: 4, cost: 1, ap: 1, hp: 2,
    traits: ['ZAFT', 'Coordinator'],
    text: '【Burst】Add this card to your hand.\n【When Linked】During this turn, this Unit may choose an active enemy Unit that is Lv.5 or lower as its attack target.',
    tip: 'Link him onto Aegis and attack an active Unit the same turn: no waiting for it to rest.',
  },
  'ST04-012': {
    id: 'ST04-012', name: 'Striker Pack', type: 'COMMAND', color: 'White', level: 4, cost: 2,
    traits: [], timing: ['Main'],
    text: '【Burst】If you have no (Earth Alliance) Unit tokens in play, deploy 1 [Aile Strike Gundam]((Earth Alliance)･AP3･HP3･<Blocker>) Unit token.\n【Main】If you have no (Earth Alliance) Unit tokens in play, deploy 1 [Sword Strike Gundam]((Earth Alliance)･AP4･HP2･<Blocker>) or 1 [Launcher Strike Gundam]((Earth Alliance)･AP2･HP4･<Blocker>) Unit token.',
    tip: 'A Blocker token on demand. Sword to kill, Launcher to wall.',
  },
  'ST04-013': {
    id: 'ST04-013', name: 'Hawk of Endymion', type: 'COMMAND', color: 'White', level: 2, cost: 1, ap: 1, hp: 0,
    traits: ['Earth Alliance'], timing: ['Main', 'Action'], pilotName: 'Mu La Flaga',
    text: "【Main】/【Action】Choose 1 enemy Unit with 3 or less HP. Return it to its owner's hand.\n【Pilot】[Mu La Flaga]",
    tip: 'Bounce an attacker mid-battle and its attack fizzles. White disruption at its best.',
  },
  'ST04-014': {
    id: 'ST04-014', name: 'The Magic Bullet of Dusk', type: 'COMMAND', color: 'Red', level: 3, cost: 1, ap: 0, hp: 1,
    traits: ['ZAFT', 'Coordinator'], timing: ['Main', 'Action'], pilotName: 'Miguel Ayman',
    text: '【Main】/【Action】Choose 1 friendly Unit that is Lv.2 or lower. It gains <First Strike> during this turn.\n(While this Unit is attacking, it deals damage before the enemy Unit.)\n【Pilot】[Miguel Ayman]',
    tip: "First Strike on Miguel's Ginn: 3 AP kills first and takes nothing back.",
  },
  'ST04-015': {
    id: 'ST04-015', name: 'Archangel', type: 'BASE', color: 'White', level: 3, cost: 1, ap: 0, hp: 5,
    traits: ['Earth Alliance', 'Warship'], zones: ['Space', 'Earth'],
    text: "【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand.\n【Activate･Main】【Once per Turn】②：Choose 1 friendly Unit with <Blocker>. Set it as active. It can't attack during this turn.",
    tip: 'Attack with a Blocker, then pay 2 to stand it back up as a defender.',
  },
  'ST04-016': {
    id: 'ST04-016', name: 'Vesalius', type: 'BASE', color: 'Red', level: 3, cost: 1, ap: 0, hp: 5,
    traits: ['ZAFT', 'Warship'], zones: ['Space'],
    text: '【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand.\n【Activate･Main】Rest this Base：Choose 1 friendly Unit. It gets AP+1 during this turn.',
    tip: 'Free +1 AP every turn: rest it before your key attack.',
  },

  // ---------- ST05 Iron Bloom (Purple / White) ----------
  'ST05-001': {
    id: 'ST05-001', name: 'Gundam Barbatos 4th Form', type: 'UNIT', color: 'Purple', level: 6, cost: 4, ap: 4, hp: 5,
    traits: ['Tekkadan', 'Gundam Frame'], link: ['Mikazuki Augus'], zones: ['Space', 'Earth'],
    text: '【Deploy】Choose 1 of your other Units. Deal 1 damage to it. It gets AP+1 during this turn.\nWhile this is damaged, it gains <Suppression>.\n(Damage to Shields by an attack is dealt to the first 2 cards simultaneously.)',
    tip: 'Purple wants its own Units hurt. Damaged, Barbatos breaks two Shields per hit.',
  },
  'ST05-002': {
    id: 'ST05-002', name: 'Gundam Barbatos 2nd Form', type: 'UNIT', color: 'Purple', level: 4, cost: 2, ap: 2, hp: 4,
    traits: ['Tekkadan', 'Gundam Frame'], link: ['Mikazuki Augus'], zones: ['Space', 'Earth'],
    text: 'While this Unit is damaged, it gets AP+2.',
    tip: 'A 2/4 that becomes 4/3 after one damage. Ping it yourself with Mobile Worker or Mikazuki.',
  },
  'ST05-003': {
    id: 'ST05-003', name: 'CGS Mobile Worker', type: 'UNIT', color: 'Purple', level: 1, cost: 1, ap: 0, hp: 2,
    traits: ['Tekkadan'], zones: ['Earth'],
    text: '【Activate･Main】Rest this Unit：Choose 1 of your Units. Deal 1 damage to it. It gets AP+1 during this turn.',
    tip: 'The engine: rest it to damage (and buff) your own Unit, turning on Purple\'s damaged bonuses.',
  },
  'ST05-004': {
    id: 'ST05-004', name: 'Graze Custom', type: 'UNIT', color: 'Purple', level: 2, cost: 1, ap: 2, hp: 2,
    traits: ['Tekkadan'], zones: ['Space', 'Earth'],
    text: '-',
    tip: 'Curve filler.',
  },
  'ST05-005': {
    id: 'ST05-005', name: 'Gundam Gusion Rebake', type: 'UNIT', color: 'Purple', level: 4, cost: 3, ap: 3, hp: 4,
    traits: ['Tekkadan', 'Gundam Frame'], link: ['Akihiro Altland'], zones: ['Space', 'Earth'],
    text: '【Destroyed】Choose 1 enemy Unit with 4 or less AP. Rest it.',
    tip: 'Even dying helps: it rests an enemy Unit so your next attacker has a target.',
  },
  'ST05-006': {
    id: 'ST05-006', name: 'Hyakuren', type: 'UNIT', color: 'Purple', level: 3, cost: 2, ap: 4, hp: 3,
    traits: ['Teiwaz'], zones: ['Space'],
    text: '-',
    tip: '4 AP for 2 cost. Purple pays for stats with fragility elsewhere.',
  },
  'ST05-007': {
    id: 'ST05-007', name: "McGillis' Schwalbe Graze", type: 'UNIT', color: 'White', level: 4, cost: 3, ap: 4, hp: 2,
    traits: ['Gjallarhorn'], link: ['McGillis Fareed'], zones: ['Space', 'Earth'],
    text: '<Blocker> (Rest this Unit to change the attack target to it.)\n【When Paired】Choose 1 enemy Unit that is Lv.3 or lower. It gets AP-2 during this turn.',
    keywords: { blocker: true },
    tip: 'A hard-hitting Blocker; pairing shrinks a small enemy so you can kill it safely.',
  },
  'ST05-008': {
    id: 'ST05-008', name: 'Graze Commander Type', type: 'UNIT', color: 'White', level: 3, cost: 2, ap: 3, hp: 2,
    traits: ['Gjallarhorn'], link: ['(Gjallarhorn)'], zones: ['Space', 'Earth'],
    text: '<Blocker> (Rest this Unit to change the attack target to it.)',
    keywords: { blocker: true },
    tip: 'Links with any Gjallarhorn pilot (McGillis).',
  },
  'ST05-009': {
    id: 'ST05-009', name: 'Graze', type: 'UNIT', color: 'White', level: 2, cost: 1, ap: 2, hp: 2,
    traits: ['Gjallarhorn'], zones: ['Space', 'Earth'],
    text: '-',
    tip: 'Efficient early body.',
  },
  'ST05-010': {
    id: 'ST05-010', name: 'Mikazuki Augus', type: 'PILOT', color: 'Purple', level: 4, cost: 1, ap: 2, hp: 1,
    traits: ['Tekkadan', 'Alaya-Vijnana'],
    text: '【Burst】Add this card to your hand.\n【When Paired】Choose 1 of your Units and 1 enemy Unit. Deal 1 damage to them.',
    tip: 'Damages your Barbatos (turning on its bonus) and an enemy at the same time.',
  },
  'ST05-011': {
    id: 'ST05-011', name: 'Akihiro Altland', type: 'PILOT', color: 'Purple', level: 3, cost: 1, ap: 1, hp: 1,
    traits: ['Tekkadan', 'Alaya-Vijnana'],
    text: '【Burst】Add this card to your hand.\n【During Link】During your turn, when this Unit destroys an enemy Unit with battle damage, choose 1 (Tekkadan) Unit card that is Lv.2 or lower from your trash. Add it to your hand.',
    tip: 'Recursion: linked on Gusion Rebake, every kill returns a cheap Tekkadan Unit from the trash.',
  },
  'ST05-012': {
    id: 'ST05-012', name: 'McGillis Fareed', type: 'PILOT', color: 'White', level: 4, cost: 1, ap: 2, hp: 1,
    traits: ['Gjallarhorn'],
    text: '【Burst】Add this card to your hand.\n【When Paired】If you have 2 or more other (Gjallarhorn)/(Tekkadan) Units in play, choose 1 enemy Unit with 3 or less HP. Rest it.',
    tip: 'With a board, pairing him rests an enemy Unit for your attackers.',
  },
  'ST05-013': {
    id: 'ST05-013', name: 'With Iron and Blood', type: 'COMMAND', color: 'Purple', level: 2, cost: 1,
    traits: [], timing: ['Main', 'Action'],
    text: '【Main】/【Action】Choose 1 of your Units. Deal 1 damage to it. It gets AP+3 during this turn.',
    tip: 'Self-damage for +3 AP, playable mid-battle. Also turns on Barbatos.',
  },
  'ST05-014': {
    id: 'ST05-014', name: 'Fatal Strike', type: 'COMMAND', color: 'Purple', level: 4, cost: 2,
    traits: [], timing: ['Main'],
    text: '【Burst】Choose 1 enemy Unit. Deal 1 damage to it.\n【Main】Choose 1 enemy Unit that is Lv.3 or lower. Destroy it.',
    tip: 'Hard removal for small Units; as a Burst it pings instead.',
  },
  'ST05-015': {
    id: 'ST05-015', name: 'Isaribi', type: 'BASE', color: 'Purple', level: 3, cost: 1, ap: 0, hp: 5,
    traits: ['Tekkadan', 'Warship'], zones: ['Space'],
    text: '【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand.\n【Activate･Main】Rest this Base：Choose 1 of your damaged Units. It gets AP+2 during this turn.',
    tip: 'Rewards the self-damage plan: +2 AP to a damaged Unit every turn.',
  },

  // ---------- ST06 Clan Unity (Red / Green) ----------
  'ST06-001': { id: 'ST06-001', name: 'GQuuuuuuX (Omega Psycommu)', type: 'UNIT', color: 'Red', level: 5, cost: 3, ap: 4, hp: 4, traits: ['Clan'], link: ['Amate Yuzuriha (Machu)'], zones: ['Space', 'Earth'],
    text: '【When Linked】If another friendly (Clan) Unit is in play, this gains <First Strike> during this turn.\n(While this Unit is attacking, it deals damage before the enemy Unit.)',
    tip: 'Link Machu with another Clan Unit out and it strikes first the turn it lands: a 6 AP first strike kills almost anything for free.' },
  'ST06-002': { id: 'ST06-002', name: 'GQuuuuuuX (Omega Psycommu)', type: 'UNIT', color: 'Red', level: 4, cost: 3, ap: 4, hp: 2, traits: ['Clan'], link: ['Amate Yuzuriha (Machu)'], zones: ['Space', 'Earth'],
    text: '【Deploy】If another friendly (Clan) Unit is in play, choose 1 enemy Unit. Deal 1 damage to it.', tip: 'Glass cannon that pings on arrival when you already have a Clan Unit.' },
  'ST06-003': { id: 'ST06-003', name: "Gaia's Rick Dom (GQ)", type: 'UNIT', color: 'Red', level: 2, cost: 2, ap: 2, hp: 2, traits: ['Clan'], link: ['Gaia'], zones: ['Space', 'Earth'],
    text: '【Activate･Main】<Support 1> (Rest this Unit. 1 other friendly Unit gets AP+(specified amount) during this turn.)', keywords: { support: 1 }, tip: 'Support battery. Ruthless Tactics pairs as Gaia (GQ) to link it.' },
  'ST06-004': { id: 'ST06-004', name: 'Gelgoog (GQ)', type: 'UNIT', color: 'Red', level: 2, cost: 1, ap: 2, hp: 2, traits: ['Zeon'], zones: ['Space', 'Earth'], text: '-', tip: 'Efficient early body.' },
  'ST06-005': { id: 'ST06-005', name: 'Red Gundam', type: 'UNIT', color: 'Green', level: 4, cost: 3, ap: 4, hp: 3, traits: ['Clan'], link: ['Shuji Itō'], zones: ['Space', 'Earth'],
    text: "<Breach 1> (When this Unit's attack destroys an enemy Unit, deal the specified amount of damage to the first card in that opponent's shield area.)\n【Attack】Choose 1 to 2 friendly (Clan) Units. They get AP+2 during this turn.", keywords: { breach: 1 },
    tip: 'Attack with it first: the AP+2 on two Clan Units powers up your other attacks this turn.' },
  'ST06-006': { id: 'ST06-006', name: 'Red Gundam', type: 'UNIT', color: 'Green', level: 4, cost: 2, ap: 3, hp: 4, traits: ['Clan'], link: ['Shuji Itō'], zones: ['Space', 'Earth'], text: '-', tip: 'Sturdy 3/4 for 2.' },
  'ST06-007': { id: 'ST06-007', name: "Ortega's Rick Dom (GQ)", type: 'UNIT', color: 'Green', level: 3, cost: 2, ap: 3, hp: 2, traits: ['Clan'], link: ['Ortega'], zones: ['Space', 'Earth'],
    text: '【Deploy】Choose 1 of your other (Clan) Units. During this turn, it may choose an active enemy Unit with 3 or less AP as its attack target.', tip: 'Lets a Clan Unit attack an active small Unit this turn: deploy it before you attack.' },
  'ST06-008': { id: 'ST06-008', name: "Sugai's Gelgoog (GQ)", type: 'UNIT', color: 'Green', level: 3, cost: 2, ap: 3, hp: 3, traits: ['Clan'], link: ['(Clan)'], zones: ['Space', 'Earth'], text: '-', tip: 'Links with any Clan pilot.' },
  'ST06-009': { id: 'ST06-009', name: 'Amate Yuzuriha (Machu)', type: 'PILOT', color: 'Red', level: 4, cost: 1, ap: 2, hp: 1, traits: ['Clan', 'Newtype'],
    text: '【Burst】Add this card to your hand.\n【When Linked】Look at the top card of your deck. If it is a (Clan) card, you may reveal it and add it to your hand. Return any remaining card to the bottom of your deck.', tip: 'Links both GQuuuuuuX forms and often draws a card.' },
  'ST06-010': { id: 'ST06-010', name: 'Shuji Itō', type: 'PILOT', color: 'Green', level: 4, cost: 1, ap: 1, hp: 2, traits: ['Clan', 'Newtype'],
    text: '【Burst】Add this card to your hand.\n【During Link】【Attack】If you have a (Clan) Unit in play, look at the top card of your deck. Return it to the top or bottom of your deck.', tip: 'Linked on Red Gundam, every attack filters your next draw.' },
  'ST06-011': { id: 'ST06-011', name: 'Ruthless Tactics', type: 'COMMAND', color: 'Red', level: 3, cost: 1, ap: 1, hp: 0, traits: ['Clan'], timing: ['Main', 'Action'], pilotName: 'Gaia (GQ)',
    text: '【Main】/【Action】Choose 1 to 2 friendly (Clan) Units. They get AP+2 during this turn.\n【Pilot】[Gaia (GQ)]', tip: 'A two-Unit pump in the action step, or a Pilot for Gaia\'s Rick Dom.' },
  'ST06-012': { id: 'ST06-012', name: 'Schoolgirl and Smuggler', type: 'COMMAND', color: 'Green', level: 1, cost: 1, traits: [], timing: ['Main'],
    text: '【Main】Look at the top 3 cards of your deck. You may reveal 1 (Clan) Unit card/Pilot card among them and add it to your hand. Return the remaining cards randomly to the bottom of your deck.', tip: 'Cheap card selection: find the pilot that links your Unit.' },
  'ST06-013': { id: 'ST06-013', name: 'Fierce Unity', type: 'COMMAND', color: 'Green', level: 3, cost: 1, ap: 1, hp: 0, traits: ['Clan'], timing: ['Action'], pilotName: 'Ortega (GQ)',
    text: "【Action】Choose 1 to 2 friendly (Clan) Units. They can't receive battle damage from enemy Units that are Lv.2 or lower during this turn.\n【Pilot】[Ortega (GQ)]", tip: 'Blanks small attackers for a turn, or pairs as Ortega to link his Rick Dom.' },
  'ST06-014': { id: 'ST06-014', name: 'Clan Battle', type: 'BASE', color: 'Red', level: 3, cost: 1, ap: 0, hp: 5, traits: ['Clan', 'Stronghold'], zones: ['Space', 'Earth'],
    text: '【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand.\n【Activate･Main】Rest this Base：If a friendly (Clan) Link Unit is in play, choose 1 friendly Unit. It gets AP+2 during this turn.', tip: 'Free +2 AP each turn once you have a Clan Link Unit.' },
  'ST06-015': { id: 'ST06-015', name: 'Kaneban Co., Ltd.', type: 'BASE', color: 'Green', level: 4, cost: 2, ap: 0, hp: 5, traits: ['Clan', 'Stronghold'], zones: ['Space', 'Earth'],
    text: "【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand.\n【Once per Turn】When a friendly (Clan) Unit links, it gains <Breach 3> during this turn.\n(When this Unit's attack destroys an enemy Unit, deal the specified amount of damage to the first card in that opponent's shield area.)", tip: 'Every link becomes a Breach 3 threat the turn it happens.' },

  // ---------- ST07 Celestial Drive (Purple / Green) ----------
  'ST07-001': { id: 'ST07-001', name: 'Gundam Exia', type: 'UNIT', color: 'Purple', level: 5, cost: 4, ap: 4, hp: 4, traits: ['CB', 'GN Drive'], link: ['Setsuna F. Seiei'], zones: ['Space', 'Earth'],
    text: 'At the end of your turn, if there are 7 or more (CB) cards in your trash, choose 1 of your Resources. Set it as active.\n【When Paired】Place the top 2 cards of your deck into your trash. If you place a (CB) card with this effect, draw 1.', tip: 'Fills the trash for the 7-CB payoffs and usually draws a card when Setsuna lands.' },
  'ST07-002': { id: 'ST07-002', name: 'Gundam Exia', type: 'UNIT', color: 'Purple', level: 4, cost: 2, ap: 4, hp: 3, traits: ['CB', 'GN Drive'], link: ['Setsuna F. Seiei'], zones: ['Space', 'Earth'], text: '-', tip: '4 AP for 2: a bargain.' },
  'ST07-003': { id: 'ST07-003', name: 'Gundam Virtue', type: 'UNIT', color: 'Purple', level: 5, cost: 3, ap: 5, hp: 4, traits: ['CB', 'GN Drive'], link: ['Tieria Erde'], zones: ['Space', 'Earth'], text: '-', tip: '5 AP for 3. Purple stats.' },
  'ST07-004': { id: 'ST07-004', name: 'Gundam Virtue', type: 'UNIT', color: 'Purple', level: 3, cost: 2, ap: 3, hp: 3, traits: ['CB', 'GN Drive'], link: ['Tieria Erde'], zones: ['Space', 'Earth'],
    text: 'While you have a (CB) Pilot in play, this Unit gains <Blocker>.\n(Rest this Unit to change the attack target to it.)', tip: 'Becomes a 3/3 Blocker as soon as any CB Pilot is paired.' },
  'ST07-005': { id: 'ST07-005', name: 'Gundam Dynames', type: 'UNIT', color: 'Green', level: 4, cost: 3, ap: 2, hp: 4, traits: ['CB', 'GN Drive'], link: ['Lockon Stratos'], zones: ['Space', 'Earth'],
    text: 'During your turn, when this Unit destroys an enemy Unit with battle damage, this Unit recovers 2 HP.\n【During Link】This Unit gets AP+2.', tip: 'Linked it is a 5/6 that heals on every kill.' },
  'ST07-006': { id: 'ST07-006', name: 'Gundam Dynames', type: 'UNIT', color: 'Green', level: 3, cost: 2, ap: 3, hp: 3, traits: ['CB', 'GN Drive'], link: ['Lockon Stratos'], zones: ['Space', 'Earth'], text: '-', tip: 'Solid curve Unit.' },
  'ST07-007': { id: 'ST07-007', name: 'Gundam Kyrios', type: 'UNIT', color: 'Green', level: 3, cost: 2, ap: 2, hp: 3, traits: ['CB', 'GN Drive'], link: ['Allelujah Haptism', 'Hallelujah Haptism'], zones: ['Space', 'Earth'],
    text: 'During your turn, while you have a (CB) Pilot in play, this Unit gets AP+2.', tip: 'A 4 AP attacker for 2 once any CB Pilot is out.' },
  'ST07-008': { id: 'ST07-008', name: 'Gundam Kyrios (Flight Mode)', type: 'UNIT', color: 'Green', level: 2, cost: 2, ap: 3, hp: 1, traits: ['CB', 'GN Drive'], link: ['Allelujah Haptism', 'Hallelujah Haptism'], zones: ['Space', 'Earth'], text: '-', tip: 'Early aggression.' },
  'ST07-009': { id: 'ST07-009', name: 'Setsuna F. Seiei', type: 'PILOT', color: 'Purple', level: 4, cost: 1, ap: 2, hp: 1, traits: ['CB'],
    text: '【Burst】Add this card to your hand.\n【Attack】This Unit gets AP+1 during this turn. If there are 7 or more (CB) cards in your trash, all your (CB) Units get AP+1 instead.', tip: 'Late game, every attack pumps your whole CB team.' },
  'ST07-010': { id: 'ST07-010', name: 'Tieria Erde', type: 'PILOT', color: 'Purple', level: 4, cost: 1, ap: 1, hp: 1, traits: ['CB', 'Innovade'],
    text: "【Burst】Add this card to your hand.\n【Destroyed】If it is your opponent's turn and this is a (CB) Unit, draw 1.", tip: 'Your Virtue dying on their turn refunds a card.' },
  'ST07-011': { id: 'ST07-011', name: 'Lockon Stratos (Neil)', type: 'PILOT', color: 'Green', level: 4, cost: 1, ap: 1, hp: 2, traits: ['CB'],
    text: '【Burst】Add this card to your hand.\n【When Paired】If this is a (CB) Unit, it may choose an active enemy Unit whose Lv. is equal to or lower than this Unit as its attack target during this turn.', tip: 'Pair, then snipe an active Unit the same turn.' },
  'ST07-012': { id: 'ST07-012', name: 'Allelujah Haptism', type: 'PILOT', color: 'Green', level: 3, cost: 1, ap: 1, hp: 1, traits: ['CB', 'Super Soldier'],
    text: "【Burst】Add this card to your hand.\nDuring your turn, while you have a (CB) Link Unit in play, this Unit can't receive battle damage from enemy Units with 3 or less AP.", tip: 'Attack into small Units for free while a CB Link Unit is out.' },
  'ST07-013': { id: 'ST07-013', name: 'Armed Intervention', type: 'COMMAND', color: 'Purple', level: 4, cost: 1, traits: [], timing: ['Action'],
    text: '【Burst】Draw 1.\n【Action】Choose 1 rested friendly (CB) Unit. Change the attack target of the battling enemy Unit to it.', tip: 'Redirect an attack into a rested CB Unit that can take it, or that you want to trade.' },
  'ST07-014': { id: 'ST07-014', name: 'Tactical Visionary', type: 'COMMAND', color: 'Green', level: 1, cost: 1, traits: [], timing: ['Main'],
    text: '【Main】Look at the top 3 cards of your deck. You may reveal 1 (CB) Unit card/Pilot card among them and add it to your hand. Return the remaining cards randomly to the bottom of your deck.', tip: 'Cheap selection for the CB pilot you need.' },
  'ST07-015': { id: 'ST07-015', name: 'Ptolemaios', type: 'BASE', color: 'Purple', level: 2, cost: 1, ap: 0, hp: 5, traits: ['CB', 'Warship'], zones: ['Space'],
    text: "【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand.\nWhile a rested friendly (CB) Unit is in play, this Base can't receive damage from enemy Units that are Lv.3 or lower, other than Unit tokens.", tip: 'Attack with a CB Unit and the Base becomes immune to small attackers.' },

  // ---------- ST08 Flash of Radiance (Red / Blue) ----------
  'ST08-001': { id: 'ST08-001', name: 'Ξ Gundam', type: 'UNIT', color: 'Red', level: 9, cost: 8, ap: 5, hp: 5, traits: ['Mafty'], link: ['Hathaway Noa'], zones: ['Space', 'Earth'],
    text: 'While you have no Units that are Lv.6 or higher in play, this card in your hand gets Lv. -1 and cost -1 for each enemy Unit in play.\n【When Paired】Choose 1 enemy Unit with the highest Lv. Deal 3 damage to it.', tip: 'Cheaper the wider their board is. Against 4 Units it is a Lv.5, cost 4 bomb.' },
  'ST08-002': { id: 'ST08-002', name: 'Ξ Gundam', type: 'UNIT', color: 'Red', level: 5, cost: 4, ap: 4, hp: 4, traits: ['Mafty'], link: ['Hathaway Noa'], zones: ['Space', 'Earth'],
    text: '【Deploy】Choose 1 enemy Unit. Deal 1 damage to it.', tip: 'Pings on deploy: finish a wounded Unit or soften a Blocker.' },
  'ST08-003': { id: 'ST08-003', name: 'Messer (Type-F Naked) (Commander Type)', type: 'UNIT', color: 'Red', level: 4, cost: 2, ap: 4, hp: 3, traits: ['Mafty'], link: ['(Mafty)'], zones: ['Earth'], text: '-', tip: '4 AP for 2, links with any Mafty pilot.' },
  'ST08-004': { id: 'ST08-004', name: 'Messer Type-F01', type: 'UNIT', color: 'Red', level: 2, cost: 2, ap: 2, hp: 1, traits: ['Mafty'], link: ['(Mafty)'], zones: ['Earth'],
    text: '【Attack】If this Unit is attacking an enemy Unit, choose 1 enemy Unit. Deal 1 damage to it.', tip: 'Attacking a rested Unit also pings any enemy Unit.' },
  'ST08-005': { id: 'ST08-005', name: 'Messer Type-F02 Minelayer', type: 'UNIT', color: 'Red', level: 3, cost: 2, ap: 4, hp: 3, traits: ['Mafty'], zones: ['Earth'], text: '-', tip: '4 AP at Lv.3.' },
  'ST08-006': { id: 'ST08-006', name: 'Penelope', type: 'UNIT', color: 'Blue', level: 7, cost: 6, ap: 5, hp: 5, traits: ['Earth Federation'], link: ['Lane Aim'], zones: ['Space', 'Earth'],
    text: '【During Pair】【Attack】【Once per Turn】If this Unit is attacking the enemy player, reveal 1 (Earth Federation) Unit card from your hand. Return it to the bottom of your deck. If you do, draw 2.', tip: 'Turns a spare Federation Unit in hand into two fresh cards every attack.' },
  'ST08-007': { id: 'ST08-007', name: 'Penelope', type: 'UNIT', color: 'Blue', level: 5, cost: 3, ap: 5, hp: 4, traits: ['Earth Federation'], link: ['Lane Aim'], zones: ['Space', 'Earth'], text: '-', tip: '5 AP for 3.' },
  'ST08-008': { id: 'ST08-008', name: 'Gustav Karl Type-00', type: 'UNIT', color: 'Blue', level: 3, cost: 3, ap: 3, hp: 4, traits: ['Earth Federation'], zones: ['Space', 'Earth'],
    text: 'While 3 or more enemy Units are in play, this Unit gains <Blocker>.\n(Rest this Unit to change the attack target to it.)', tip: 'A wall that turns on when the opponent goes wide.' },
  'ST08-009': { id: 'ST08-009', name: 'Jegan Ground Type-A (Man Hunter)', type: 'UNIT', color: 'Blue', level: 1, cost: 1, ap: 0, hp: 1, traits: ['Earth Federation'], zones: ['Earth'],
    text: "【Deploy】Choose 1 rested enemy Unit that is Lv.2 or lower. It won't be set as active during the start phase of your opponent's next turn.", tip: 'Keeps a small Unit rested through their turn: it stays a target for you.' },
  'ST08-010': { id: 'ST08-010', name: 'Hathaway Noa', type: 'PILOT', color: 'Red', level: 4, cost: 1, ap: 2, hp: 1, traits: ['Mafty', 'Newtype'],
    text: '【Burst】Add this card to your hand.\n【When Paired】If this is a (Mafty) Unit, choose 1 of your (Mafty) Units. During this turn, it may choose a damaged active enemy Unit as its attack target.', tip: 'Finish damaged Units even when they are active.' },
  'ST08-011': { id: 'ST08-011', name: 'Lane Aim', type: 'PILOT', color: 'Blue', level: 4, cost: 1, ap: 2, hp: 1, traits: ['Earth Federation'],
    text: "【Burst】Add this card to your hand.\nWhen you draw with an effect, if this is a blue Unit, it gains <High-Maneuver> during this turn.\n(This Unit can't be blocked.)", tip: 'On Penelope: attack, draw 2, and the next attack cannot be blocked.' },
  'ST08-012': { id: 'ST08-012', name: 'Words for Hathaway', type: 'COMMAND', color: 'Red', level: 3, cost: 1, ap: 1, hp: 0, traits: ['Mafty'], timing: ['Main'], pilotName: 'Gawman Nobile',
    text: "【Main】Choose 1 friendly Link Unit. It gains <Breach 1> during this turn.\n(When this Unit's attack destroys an enemy Unit, deal the specified amount of damage to the first card in that opponent's shield area.)\n【Pilot】[Gawman Nobile]", tip: 'Or pair it as a Mafty pilot to link a Messer.' },
  'ST08-013': { id: 'ST08-013', name: 'Lady Luck', type: 'COMMAND', color: 'Red', level: 5, cost: 1, traits: [], timing: ['Main', 'Action'],
    text: '【Main】/【Action】Choose 1 enemy Unit. Deal 1 damage to it. If a friendly (Mafty) Link Unit is in play, deal 2 damage instead.', tip: 'Cheap removal, doubled with a Mafty Link Unit.' },
  'ST08-014': { id: 'ST08-014', name: 'Valiant', type: 'BASE', color: 'Red', level: 2, cost: 1, ap: 0, hp: 5, traits: ['Mafty', 'Warship'], zones: ['Earth'],
    text: '【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand. Then, choose 1 of your Units. It gets AP+2 during this turn.', tip: 'Deploy before attacking for a surprise +2.' },
  'ST08-015': { id: 'ST08-015', name: 'Davao', type: 'BASE', color: 'Blue', level: 3, cost: 1, ap: 0, hp: 5, traits: ['Earth Federation', 'Stronghold'], zones: ['Earth'],
    text: '【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand.\n【Activate･Main】【Once per Turn】②：Choose 1 of your Units. It recovers 2 HP.', tip: 'Repeatable healing for 2 Resources.' },

  // ---------- ST09 Destiny Ignition (Purple / Red; "Ultimate Deck" with White extras) ----------
  'ST09-001': { id: 'ST09-001', name: 'Impulse Gundam', type: 'UNIT', color: 'Purple', level: 3, cost: 2, ap: 3, hp: 3, traits: ['ZAFT', 'Minerva Squad'], link: ['Shinn Asuka'], zones: ['Space', 'Earth'],
    text: '【Activate･Main】②, return this Unit to the bottom of its owner\'s deck：Choose 1 Unit card with "Impulse Gundam" in its card name that is Lv.4 or higher from your trash. Deploy it.', tip: 'A Lv.3 body that swaps itself for a Sword or Blast Impulse from your trash. Discard or lose an Impulse first, then upgrade for 2.' },
  'ST09-002': { id: 'ST09-002', name: 'Force Impulse Gundam', type: 'UNIT', color: 'Purple', level: 5, cost: 4, ap: 5, hp: 4, traits: ['ZAFT', 'Minerva Squad'], link: ['Shinn Asuka'], zones: ['Space', 'Earth'],
    text: '【Destroyed】Choose 1 (Minerva Squad) Unit card without "Force Impulse Gundam" in its card name from your trash. Add it to your hand.', tip: 'Trades happily: when it dies it refunds a Minerva Squad Unit from the trash.' },
  'ST09-003': { id: 'ST09-003', name: 'Saviour Gundam', type: 'UNIT', color: 'Red', level: 6, cost: 5, ap: 5, hp: 4, traits: ['ZAFT', 'Minerva Squad'], link: ['Athrun Zala'], zones: ['Space', 'Earth'],
    text: '<Breach 3> (When this Unit\'s attack destroys an enemy Unit, deal the specified amount of damage to the first card in that opponent\'s shield area.)\n【When Linked】If there are 5 or more purple cards in your trash, deal 2 damage to all Units with 5 or less AP.', keywords: { breach: 3 },
    tip: 'Link Athrun with 5+ purple cards in your trash for a board-wide 2 damage. It hits your own small Units too, so count first.' },
  'ST09-004': { id: 'ST09-004', name: 'Freedom Gundam', type: 'UNIT', color: 'White', level: 6, cost: 5, ap: 4, hp: 5, traits: ['Orb'], link: ['Kira Yamato'], zones: ['Space', 'Earth'],
    text: '<Blocker> (Rest this Unit to change the attack target to it.)\nWhile a friendly Base in play, this Unit gains <Suppression>.\n(Damage to Shields by an attack is dealt to the first 2 cards simultaneously.)', keywords: { blocker: true },
    tip: 'Keep a Base out and Freedom breaks two Shields per hit while still blocking on defense.' },
  'ST09-005': { id: 'ST09-005', name: 'Zaku Warrior', type: 'UNIT', color: 'Purple', level: 2, cost: 1, ap: 2, hp: 2, traits: ['ZAFT', 'Minerva Squad'], zones: ['Space', 'Earth'], text: '-', tip: 'Cheap Minerva Squad body; Force Impulse can bring it back.' },
  'ST09-006': { id: 'ST09-006', name: 'Sword Impulse Gundam', type: 'UNIT', color: 'Purple', level: 4, cost: 2, ap: 4, hp: 2, traits: ['ZAFT', 'Minerva Squad'], link: ['(Coordinator)', '(Minerva Squad)'], zones: ['Space', 'Earth'],
    text: '【Deploy】If you deploy this Unit from your trash, choose 1 enemy Unit that is Lv.3 or lower. Destroy it.', tip: 'Weak from hand, deadly from the trash: Impulse Gundam\'s swap turns it into removal.' },
  'ST09-007': { id: 'ST09-007', name: 'Blast Impulse Gundam', type: 'UNIT', color: 'Purple', level: 5, cost: 3, ap: 5, hp: 3, traits: ['ZAFT', 'Minerva Squad'], link: ['Shinn Asuka'], zones: ['Space', 'Earth'],
    text: '<Blocker> (Rest this Unit to change the attack target to it.)', keywords: { blocker: true }, tip: '5 AP Blocker for 3. Kills most attackers that run into it.' },
  'ST09-008': { id: 'ST09-008', name: 'Shinn Asuka', type: 'PILOT', color: 'Purple', level: 4, cost: 1, ap: 3, hp: 0, traits: ['ZAFT', 'Minerva Squad', 'Coordinator'],
    text: '【Burst】Add this card to your hand.\n【Attack】If this is a (Minerva Squad) Unit, choose 1 of your Resources. Set it as active.', tip: '+3 AP and a refunded Resource every attack on a Minerva Squad Unit.' },
  'ST09-009': { id: 'ST09-009', name: 'Giant Killing', type: 'COMMAND', color: 'Purple', level: 4, cost: 3, traits: [], timing: ['Main', 'Action'],
    text: '【Main】/【Action】Choose 1 active enemy Unit with 4 or less AP. Destroy it.', tip: 'Hard removal for an active Unit: use it on a Blocker before you attack, or on a paired Unit.' },
  'ST09-010': { id: 'ST09-010', name: 'Minerva', type: 'BASE', color: 'Purple', level: 2, cost: 1, ap: 0, hp: 5, traits: ['ZAFT', 'Minerva Squad', 'Warship'], zones: ['Space', 'Earth'],
    text: '【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand. Then, if it is your turn, look at the top 2 cards of your deck and return 1 to the top. Place the remaining card into your trash.', tip: 'Fills your trash (for Impulse and Saviour) while fixing your next draw.' },
  'GD01-049': { id: 'GD01-049', name: 'Blitz Gundam', type: 'UNIT', color: 'Red', level: 4, cost: 3, ap: 3, hp: 3, traits: ['ZAFT'], link: ['Nicol Amarfi'], zones: ['Space', 'Earth'],
    text: '【Deploy】Choose 1 of your (ZAFT) Units with 5 or more AP. It gains <First Strike> during this turn.\n(While this Unit is attacking, it deals damage before the enemy Unit.)', tip: 'Deploy it after pairing Shinn: a 5+ AP ZAFT Unit with First Strike kills without taking damage back.' },
  'GD01-054': { id: 'GD01-054', name: 'Duel Gundam', type: 'UNIT', color: 'Red', level: 3, cost: 2, ap: 3, hp: 3, traits: ['ZAFT'], link: ['(ZAFT)'], zones: ['Space', 'Earth'],
    text: 'While this Unit has 5 or more AP, it gains <Breach 3>.\n(When this Unit\'s attack destroys an enemy Unit, deal the specified amount of damage to the first card in that opponent\'s shield area.)', tip: 'Any ZAFT Pilot links it; Shinn\'s +3 AP turns on Breach 3.' },
  'GD01-111': { id: 'GD01-111', name: 'Battle of Aces', type: 'COMMAND', color: 'Red', level: 3, cost: 2, traits: [], timing: ['Main', 'Action'],
    text: '【Burst】Choose 1 enemy Unit. Deal 2 damage to it.\n【Main】/【Action】Choose 1 damaged enemy Unit. Deal 3 damage to it.', tip: 'Finishes anything that survived a battle. Hold it for the action step of your own attack.' },
  'GD01-118': { id: 'GD01-118', name: 'Overflowing Affection', type: 'COMMAND', color: 'White', level: 2, cost: 1, traits: [], timing: ['Main'],
    text: '【Main】Draw 2. Then, discard 1.', tip: 'Card quality for 1, and the discard feeds the trash.' },
  'GD02-076': { id: 'GD02-076', name: 'Buster Gundam', type: 'UNIT', color: 'White', level: 4, cost: 3, ap: 4, hp: 3, traits: ['Triple Ship Alliance'], link: ['(Coordinator)'], zones: ['Space', 'Earth'],
    text: 'While this Unit has 5 or more AP, it gains <Blocker>.\n(Rest this Unit to change the attack target to it.)', tip: 'Pair any Coordinator (Kira, Shinn, Athrun) and it becomes a 5+ AP Blocker.' },
  'GD02-110': { id: 'GD02-110', name: 'Awakened Power', type: 'COMMAND', color: 'Purple', level: 6, cost: 2, traits: [], timing: ['Main'],
    text: '【Main】Choose 1 Unit card that is Lv.5 or lower from your trash. Pay its cost to deploy it.', tip: 'Re-deploys a fallen Unit. Sword Impulse from the trash also destroys a Lv.3-or-lower enemy.' },

  // ---------- ST10 Generation Pulse (Blue / White) ----------
  'ST10-001': { id: 'ST10-001', name: 'Zeta Gundam (EX)', type: 'UNIT', color: 'Blue', level: 7, cost: 6, ap: 5, hp: 5, traits: ['G Generation'], link: ['Kamille Bidan'], zones: ['Space', 'Earth'],
    text: "When this Unit destroys an enemy shield area card with battle damage, set it as active. It can't choose the same enemy player or enemy team as its attack target during this turn.", tip: 'Break a Shield, stand back up, then attack a rested enemy Unit in the same turn.' },
  'ST10-002': { id: 'ST10-002', name: 'Zeta Gundam', type: 'UNIT', color: 'Blue', level: 5, cost: 4, ap: 4, hp: 4, traits: ['G Generation'], link: ['(Support)', 'Kamille Bidan'], zones: ['Space', 'Earth'],
    text: '【Deploy・Development 2】You may exile the specified number of (G Generation) cards in your trash from the game. If you do, activate the following effect:\n■Choose 1 enemy Unit with 4 or less HP. Rest it.', tip: 'Development: pay with cards from your trash. Rest a target on deploy, then attack it.' },
  'ST10-003': { id: 'ST10-003', name: 'Gundam Mk-II (AEUG)', type: 'UNIT', color: 'Blue', level: 2, cost: 2, ap: 2, hp: 2, traits: ['G Generation'], link: ['Kamille Bidan'], zones: ['Space', 'Earth'], text: '-', tip: 'Early body that Kamille links.' },
  'ST10-004': { id: 'ST10-004', name: 'Super Gundam', type: 'UNIT', color: 'Blue', level: 4, cost: 3, ap: 3, hp: 4, traits: ['G Generation'], zones: ['Space', 'Earth'],
    text: '<Repair 2> (At the end of your turn, this Unit recovers the specified number of HP.)', keywords: { repair: 2 }, tip: 'Shrugs off chip damage every turn.' },
  'ST10-005': { id: 'ST10-005', name: 'Nemo', type: 'UNIT', color: 'Blue', level: 2, cost: 1, ap: 2, hp: 2, traits: ['G Generation'], zones: ['Space', 'Earth'], text: '-', tip: '2/2 for 1. Development fodder once it dies.' },
  'ST10-006': { id: 'ST10-006', name: 'Phoenix Gundam (Power Unleashed) (EX)', type: 'UNIT', color: 'White', level: 5, cost: 3, ap: 4, hp: 4, traits: ['G Generation'], link: ['Mark Guilder'], zones: ['Space', 'Earth'],
    text: "【During Pair】During your turn, when this Unit destroys an enemy Unit with battle damage, choose 1 enemy Unit with 3 or less HP. Return it to its owner's hand.", tip: 'Paired, every kill also bounces a second small Unit (and its Pilot).' },
  'ST10-007': { id: 'ST10-007', name: 'Gundam Barbatos 4th Form', type: 'UNIT', color: 'White', level: 6, cost: 5, ap: 4, hp: 5, traits: ['G Generation'], link: ['(G Generation)'], zones: ['Space', 'Earth'],
    text: '【When Linked・Development 2】You may exile the specified number of (G Generation) cards in your trash from the game. If you do, activate the following effect:\n■Choose 1 Command card that is Lv.4 or lower from your trash. Add it to your hand.', tip: 'Any G Generation Pilot links it and buys back a Command from the trash.' },
  'ST10-008': { id: 'ST10-008', name: 'Gundam Barbatos 1st Form', type: 'UNIT', color: 'White', level: 4, cost: 3, ap: 4, hp: 3, traits: ['G Generation'], link: ['(G Generation)'], zones: ['Space', 'Earth'],
    text: '【Deploy・Development 2】You may exile the specified number of (G Generation) cards in your trash from the game. If you do, activate the following effect:\n■Draw a number of cards equal to the number of enemy players. Then, discard the same number of cards you drew with this effect.', tip: 'Cycles a card on deploy if you feed it two trash cards.' },
  'ST10-009': { id: 'ST10-009', name: 'Graze Duel Type', type: 'UNIT', color: 'White', level: 3, cost: 2, ap: 2, hp: 3, traits: ['G Generation'], link: ['(G Generation)'], zones: ['Space', 'Earth'],
    text: '<Blocker> (Rest this Unit to change the attack target to it.)', keywords: { blocker: true }, tip: 'Sturdy early Blocker that links with any G Generation Pilot.' },
  'ST10-010': { id: 'ST10-010', name: 'Mobile Worker (Tekkadan)', type: 'UNIT', color: 'White', level: 2, cost: 2, ap: 2, hp: 1, traits: ['G Generation'], zones: ['Earth'],
    text: '<Blocker> (Rest this Unit to change the attack target to it.)', keywords: { blocker: true }, tip: 'A chump Blocker: it saves a Shield once.' },
  'ST10-011': { id: 'ST10-011', name: 'Kamille Bidan', type: 'PILOT', color: 'Blue', level: 4, cost: 1, ap: 2, hp: 1, traits: ['G Generation', 'Attack'],
    text: '【Burst】Add this card to your hand.\n【When Linked】If 2 or more rested Units are in play, choose 1 enemy Unit whose Lv. is equal to or lower than this Unit. Rest it.', tip: 'Link after your first attacks (2+ rested Units) to rest another target.' },
  'ST10-012': { id: 'ST10-012', name: 'Mark Guilder', type: 'PILOT', color: 'White', level: 4, cost: 1, ap: 2, hp: 1, traits: ['G Generation', 'Support'],
    text: '【Burst】Add this card to your hand.\n【When Paired】Choose 1 enemy Unit that is Lv.5 or lower. It gets AP-2 during this turn.', tip: 'Pair before attacking into a Unit: AP-2 makes the trade safe. Also links Zeta Gundam via the (Support) trait.' },
  'ST10-013': { id: 'ST10-013', name: 'Tactical Training', type: 'COMMAND', color: 'Blue', level: 3, cost: 1, traits: [], timing: ['Main', 'Action'],
    text: '【Burst】Add this card to your hand.\n【Main】/【Action】Choose 1 (G Generation) Unit that is Lv.5 or higher. It recovers 2 HP and gets AP+2 during this turn.', tip: 'Heal and pump a big Unit mid-battle for 1 Resource.' },
  'ST10-014': { id: 'ST10-014', name: 'Unlocking the Development Diagram', type: 'COMMAND', color: 'Blue', level: 4, cost: 4, traits: [], timing: ['Main'],
    text: 'When playing this card from your hand, you may discard 1 (G Generation) Unit card. If you do, play this card as if it has 2 Lv. and cost.\n【Main】Draw 2.', tip: 'Discard a spare Unit to draw 2 for 2 (and stock the trash for Development).' },
  'ST10-015': { id: 'ST10-015', name: 'Diffuse Beam Cannon', type: 'COMMAND', color: 'White', level: 3, cost: 1, ap: 1, hp: 0, traits: ['G Generation', 'Durability'], timing: ['Action'], pilotName: 'Claire Heathrow',
    text: '【Action】If a friendly (G Generation) Unit is in play, choose 1 enemy Unit. It gets AP-3 during this battle.\n【Pilot】[Claire Heathrow]', tip: 'AP-3 in a battle, or a G Generation Pilot that links Barbatos and Graze.' },
  'ST10-016': { id: 'ST10-016', name: 'Luna Mana & Carry Base', type: 'BASE', color: 'Blue', level: 4, cost: 1, ap: 0, hp: 5, traits: ['G Generation', 'Warship'], zones: ['Space', 'Earth'],
    text: '【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand. Then, all friendly (G Generation) Units recover 1 HP.', tip: 'A Shield to hand plus a team heal.' },

  // ---------- ST11 Aquatic Assault (Blue / Purple) ----------
  'ST11-001': { id: 'ST11-001', name: "Char's Z'Gok", type: 'UNIT', color: 'Blue', level: 4, cost: 3, ap: 3, hp: 3, traits: ['Zeon', 'Marine'], link: ['Char Aznable'], zones: ['Earth'],
    text: "【During Pair】While 2 or more other friendly (Marine) Units are in play, enemy Units can't choose this Unit as their attack target.\n【Deploy】If another friendly (Marine) Unit is in play, choose 1 enemy Unit that is Lv.2 or lower. Return it to the bottom of its owner's deck.", tip: 'With two other Marines and Char aboard it cannot be attacked. Deploy it into a board to tuck a small enemy Unit.' },
  'ST11-002': { id: 'ST11-002', name: 'Acguy', type: 'UNIT', color: 'Blue', level: 3, cost: 2, ap: 3, hp: 1, traits: ['Zeon', 'Marine'], zones: ['Earth'],
    text: "During your opponent's turn, while this Unit is rested, friendly (Marine) Units with 2 or less HP can't receive enemy effect damage.", tip: 'Attack with it, and your small Marines are safe from pings on their turn.' },
  'ST11-003': { id: 'ST11-003', name: 'Zock', type: 'UNIT', color: 'Blue', level: 3, cost: 2, ap: 3, hp: 3, traits: ['Zeon', 'Marine'], zones: ['Earth'],
    text: 'While another friendly (Marine) Unit is in play, this Unit gains <Blocker>.\n(Rest this Unit to change the attack target to it.)', tip: 'A 3/3 Blocker as long as you keep a second Marine out.' },
  'ST11-004': { id: 'ST11-004', name: 'ZnO', type: 'UNIT', color: 'Blue', level: 3, cost: 3, ap: 3, hp: 2, traits: ['ZAFT', 'Marine'], link: ['Marco Morassim'], zones: ['Earth'],
    text: '【Deploy】Deploy 1 rested [GOOhN]((ZAFT) (Marine)･AP1･HP1) Unit token.', tip: 'Two Marines for one card: turns on Zock and Z\'Gok.' },
  'ST11-005': { id: 'ST11-005', name: 'Ash', type: 'UNIT', color: 'Blue', level: 5, cost: 4, ap: 4, hp: 4, traits: ['ZAFT', 'Marine'], link: ['(ZAFT)'], zones: ['Earth'],
    text: '<Repair 2> (At the end of your turn, this Unit recovers the specified number of HP.)', keywords: { repair: 2 }, tip: 'A durable mid-game Marine.' },
  'ST11-006': { id: 'ST11-006', name: 'Shamblo', type: 'UNIT', color: 'Purple', level: 6, cost: 5, ap: 4, hp: 5, traits: ['Zeon', 'Marine'], link: ['Loni Garvey'], zones: ['Earth'],
    text: "If another friendly (Marine) Unit is in play at the start of your opponent's turn, during this turn, when a friendly shield area card receives enemy effect damage, reduce it by 5.\n【Deploy】Choose 1 (Marine) Unit card from your trash. Add it to your hand.", tip: 'Refunds a Marine from the trash on deploy and blanks Breach-style effect damage to your shield area.' },
  'ST11-007': { id: 'ST11-007', name: 'Gundam Leopard', type: 'UNIT', color: 'Purple', level: 3, cost: 2, ap: 4, hp: 3, traits: ['Vulture', 'Marine'], zones: ['Earth'], text: '-', tip: '4 AP for 2 at Lv.3.' },
  'ST11-008': { id: 'ST11-008', name: 'Daughseat', type: 'UNIT', color: 'Purple', level: 2, cost: 1, ap: 2, hp: 2, traits: ['Vulture', 'Marine'], zones: ['Earth'], text: '-', tip: 'Cheap Marine count.' },
  'ST11-009': { id: 'ST11-009', name: 'Kapool', type: 'UNIT', color: 'Purple', level: 1, cost: 1, ap: 1, hp: 1, traits: ['Militia', 'Marine'], zones: ['Space', 'Earth'],
    text: "【Destroyed】If it is your opponent's turn and a friendly (Marine) Unit is in play, draw 1.", tip: 'A turn-1 Marine that draws a card when it dies on their turn.' },
  'ST11-010': { id: 'ST11-010', name: 'Abyss Gundam', type: 'UNIT', color: 'Purple', level: 4, cost: 3, ap: 4, hp: 3, traits: ['Earth Alliance', 'Phantom Pain', 'Marine'], link: ['Auel Neider'], zones: ['Space', 'Earth'],
    text: '<Blocker> (Rest this Unit to change the attack target to it.)', keywords: { blocker: true }, tip: '4 AP Blocker.' },
  'ST11-011': { id: 'ST11-011', name: 'Char Aznable', type: 'PILOT', color: 'Blue', level: 4, cost: 1, ap: 2, hp: 1, traits: ['Zeon', 'Newtype'],
    text: '【Burst】Add this card to your hand.\n【When Paired】All friendly (Marine) Units get AP+1 during this turn.', tip: 'Pair before attacking with a wide Marine board.' },
  'ST11-012': { id: 'ST11-012', name: 'Loni Garvey', type: 'PILOT', color: 'Purple', level: 4, cost: 1, ap: 2, hp: 1, traits: ['Zeon', 'Newtype'],
    text: '【Burst】Add this card to your hand.\n【When Paired】Choose 1 friendly (Marine) Unit. During this turn, when it receives battle damage from an enemy Unit, reduce it by 2.', tip: 'Damage reduction lets a Marine attack into a bigger Unit and survive.' },
  'ST11-013': { id: 'ST11-013', name: 'Poorly Planned Offensive', type: 'COMMAND', color: 'Blue', level: 4, cost: 2, traits: [], timing: ['Main', 'Action'],
    text: "【Burst】Choose 1 rested enemy Unit with 3 or less HP. Return it to its owner's hand.\n【Main】/【Action】Choose 1 rested enemy Unit with 3 or less HP. Return it to its owner's hand. If you do, draw 1.", tip: 'Bounce an attacker mid-battle and draw a card.' },
  'ST11-014': { id: 'ST11-014', name: 'The Orca of Red Sea', type: 'COMMAND', color: 'Blue', level: 3, cost: 1, ap: 1, hp: 1, traits: ['ZAFT', 'Coordinator'], timing: ['Action'], pilotName: 'Marco Morassim',
    text: "【Action】Choose 1 friendly (Marine) Unit. Enemy Units can't choose it as their attack target this turn.\n【Pilot】[Marco Morassim]", tip: 'Save a Marine from an attack, or pair it to link ZnO.' },
  'ST11-015': { id: 'ST11-015', name: 'A Twinkle from the Abyss', type: 'COMMAND', color: 'Purple', level: 5, cost: 2, traits: [], timing: ['Main'],
    text: '【Main】Choose 1 (Marine) Unit card that is Lv.4 or lower from your trash. Deploy it rested.', tip: 'A Marine back from the trash for 2, ready to block or count for your other Marines.' },
  'ST11-016': { id: 'ST11-016', name: 'Mad Angler', type: 'BASE', color: 'Blue', level: 3, cost: 1, ap: 0, hp: 5, traits: ['Zeon', 'Warship', 'Marine'], zones: ['Earth'],
    text: '【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand. Then, if 4 or more enemy Units are in play, choose 1 rested enemy Unit. Deal 2 damage to it.', tip: 'Punishes a wide board with 2 damage on deploy.' },

  // ---------- ST12 Raging Onslaught (Red / Purple) ----------
  'ST12-001': { id: 'ST12-001', name: 'Gundam Epyon', type: 'UNIT', color: 'Red', level: 7, cost: 6, ap: 5, hp: 5, traits: ['White Fang'], link: ['Zechs Merquise'], zones: ['Space', 'Earth'],
    text: '【During Pair･Lv.5 or Higher Pilot】During your turn, when this Unit destroys an enemy Unit with damage, deal 2 damage to all enemy Units with 5 or less AP.\n【Deploy】Choose 1 enemy Base. Deal 5 damage to it.', tip: 'Deploy to erase a Base. Pair Milliardo (Lv.5) and every kill splashes 2 damage across their board, chaining if that kills more.' },
  'ST12-002': { id: 'ST12-002', name: 'Shining Gundam', type: 'UNIT', color: 'Red', level: 5, cost: 4, ap: 5, hp: 4, traits: ['MF', 'Shuffle Alliance'], link: ['Domon Kasshu'], zones: ['Space', 'Earth'],
    text: '【Deploy】Choose 1 friendly Unit with 5 or more AP. It gains <Breach 3> during this turn.\n(During your turn, when this Unit destroys an enemy Unit with battle damage, deal the specified amount of damage to the first card in that opponent\'s shield area.)', tip: 'Deploy before attacking with a 5-AP Unit: a kill also hits their shield area for 3.' },
  'ST12-003': { id: 'ST12-003', name: 'Tallgeese Ⅲ', type: 'UNIT', color: 'Red', level: 5, cost: 4, ap: 4, hp: 4, traits: ['Preventer'], link: ['Zechs Merquise'], zones: ['Space', 'Earth'],
    text: '【Once per Turn】During your turn, when this Unit destroys an enemy Unit with damage, deal 1 damage to all enemy Units with 3 or less AP.', tip: 'Kill a Unit and ping every small enemy Unit.' },
  'ST12-004': { id: 'ST12-004', name: 'Gundam Exia', type: 'UNIT', color: 'Red', level: 4, cost: 3, ap: 3, hp: 4, traits: ['CB', 'GN Drive'], link: ['Setsuna F. Seiei'], zones: ['Space', 'Earth'],
    text: '<Breach 3> (During your turn, when this Unit destroys an enemy Unit with battle damage, deal the specified amount of damage to the first card in that opponent\'s shield area.)', keywords: { breach: 3 }, tip: 'Breach 3 on a 4 HP body.' },
  'ST12-005': { id: 'ST12-005', name: 'GQuuuuuuX (Omega Psycommu)', type: 'UNIT', color: 'Red', level: 3, cost: 2, ap: 3, hp: 2, traits: ['Clan'], link: ['Amate Yuzuriha (Machu)', 'Nyaan'], zones: ['Space', 'Earth'],
    text: '【Attack】You may discard 1. If you do, draw 1.', tip: 'Every attack lets you cycle a dead card and stock the trash for Banshee.' },
  'ST12-006': { id: 'ST12-006', name: 'Unicorn Gundam 02 Banshee (Destroy Mode)', type: 'UNIT', color: 'Purple', level: 6, cost: 5, ap: 5, hp: 4, traits: ['Earth Federation'], link: ['Marida Cruz'], zones: ['Space', 'Earth'],
    text: '【During Pair】【Activate･Main】Exile 4 cards in your trash from the game：This Unit gains <First Strike> during this turn.\n(While this Unit is attacking, it deals damage before the enemy Unit.)\n【Activate･Action】Exile 4 cards in your trash from the game：This Unit gains <Suppression> during this battle.\n(Damage to Shields by an attack is dealt to the first 2 cards simultaneously.)', tip: 'Your trash is fuel: 4 cards for First Strike (kill without damage back) or Suppression (two Shields at once) while attacking.' },
  'ST12-007': { id: 'ST12-007', name: 'Gyan', type: 'UNIT', color: 'Purple', level: 2, cost: 2, ap: 3, hp: 1, traits: ['Zeon'], link: ["M'Quve"], zones: ['Space', 'Earth'],
    text: '【When Linked】This Unit gains <First Strike> during this turn.\n(While this Unit is attacking, it deals damage before the enemy Unit.)', tip: "Pair Wise Leader's Pride as M'Quve: a 4 AP First Strike attacker on turn 2." },
  'ST12-008': { id: 'ST12-008', name: 'Efreet Schneid', type: 'UNIT', color: 'Purple', level: 4, cost: 2, ap: 4, hp: 3, traits: ['Zeon'], link: ['(Zeon)'], zones: ['Earth'], text: '-', tip: '4 AP for 2, links with any Zeon Pilot.' },
  'ST12-009': { id: 'ST12-009', name: 'Unicorn Gundam 02 Banshee (Unicorn Mode)', type: 'UNIT', color: 'Purple', level: 4, cost: 3, ap: 3, hp: 4, traits: ['Earth Federation'], link: ['Marida Cruz'], zones: ['Space', 'Earth'],
    text: '【Destroyed】If there is a player with 3 or less Shields, choose 1 Unit card that is Lv.6 or higher from your trash. Add it to your hand. If you do, discard 1.', tip: 'Late in the game its death fetches Banshee Destroy Mode from the trash.' },
  'ST12-010': { id: 'ST12-010', name: 'Slash Zaku Phantom', type: 'UNIT', color: 'Purple', level: 2, cost: 1, ap: 2, hp: 2, traits: ['ZAFT'], zones: ['Space', 'Earth'], text: '-', tip: 'Turn-2 pressure.' },
  'ST12-011': { id: 'ST12-011', name: 'Milliardo Peacecraft', type: 'PILOT', color: 'Red', level: 5, cost: 1, ap: 3, hp: 1, traits: ['White Fang'], alsoNamed: ['Zechs Merquise'],
    text: 'This card\'s name is also treated as [Zechs Merquise].\n【Burst】Add this card to your hand.\n【Activate･Action】【Once per Turn】Choose 1 damaged enemy Unit battling this Unit. Deal 2 damage to it.', tip: 'Links Epyon and Tallgeese Ⅲ as Zechs. In battle against a damaged Unit, fire 2 free damage before the damage step.' },
  'ST12-012': { id: 'ST12-012', name: 'Ple-Twelve', type: 'PILOT', color: 'Purple', level: 4, cost: 1, ap: 1, hp: 2, traits: ['Earth Federation', 'Cyber-Newtype'], alsoNamed: ['Marida Cruz'],
    text: 'This card\'s name is also treated as [Marida Cruz].\n【Burst】Add this card to your hand.\n【When Linked】Look at the top 2 cards of your deck and return 1 to the top. Place the remaining card into your trash. If there is a player with 3 or less Shields, add the card to your hand instead of returning it to your deck.', tip: 'Links both Banshees as Marida. Fills the trash for Destroy Mode; late game it draws instead.' },
  'ST12-013': { id: 'ST12-013', name: 'The Final Victor', type: 'COMMAND', color: 'Red', level: 6, cost: 2, traits: [], timing: ['Main'],
    text: '【Burst】Choose 1 enemy Unit. Deal 1 damage to it.\n【Main】Choose 1 enemy player. You and that player each choose 1 of your own Units. Begin a battle between them and only perform the damage step.\n(You choose first, then your opponent.)', tip: 'Force a fight: pick your biggest Unit and they must throw a Unit at it, even an active one.' },
  'ST12-014': { id: 'ST12-014', name: "Wise Leader's Pride", type: 'COMMAND', color: 'Purple', level: 3, cost: 1, ap: 1, hp: 0, traits: ['Zeon'], timing: ['Action'], pilotName: "M'Quve",
    text: '【Action】Choose 1 friendly Unit. It gains the following effect during this battle：\n■When this Unit destroys an enemy Unit with battle damage, choose 1 enemy Unit with 2 or less AP. Destroy it.\n【Pilot】[M\'Quve]', tip: "Two kills for one battle, or pair it as M'Quve to link Gyan." },
  'ST12-015': { id: 'ST12-015', name: 'Two Unicorns', type: 'COMMAND', color: 'Purple', level: 4, cost: 1, traits: [], timing: ['Action'],
    text: '【Action】When playing this card, choose 1 of the following effects and activate it：\n■Choose 1 enemy Unit that is Lv.2 or lower. Destroy it.\n■Choose 1 friendly Unit and 1 enemy Unit that is Lv.5 or higher. Deal 2 damage to them.', tip: 'Flexible: destroy a small attacker, or ping a big one (and your own Unit) for 2.' },
  'ST12-016': { id: 'ST12-016', name: 'Libra', type: 'BASE', color: 'Red', level: 3, cost: 1, ap: 0, hp: 5, traits: ['White Fang', 'Warship'], zones: ['Space'],
    text: '【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand.\n【Activate･Main】Rest this Base：If a friendly Unit paired with a Pilot has destroyed an enemy Unit with battle damage this turn, choose 1 enemy Unit that is Lv.4 or lower. Deal 1 damage to it.', tip: 'After a paired Unit kills something, rest Libra to finish a second wounded Unit.' },

  // ---------- ST13 Silent Barrage (Green / Red) ----------
  'ST13-001': { id: 'ST13-001', name: 'Qubeley', type: 'UNIT', color: 'Green', level: 7, cost: 5, ap: 5, hp: 5, traits: ['Neo Zeon'], link: ['Haman Karn'], zones: ['Space', 'Earth'],
    text: "【Once per Turn】During your turn, when you pair a Pilot with one of your Units, deploy 1 to 2 [Bit / Funnel]((Long-Range Weapon)･AP2･HP2･This Unit can't be paired with a Pilot or attack) Unit tokens.\n【Activate･Main】【Once per Turn】①：Choose 1 of your Unit tokens and 1 enemy Unit. Begin a battle between them and only perform the damage step.", tip: 'Pairing any Pilot makes two Funnels; for 1 Resource a Funnel fights an enemy Unit directly, even an active one.' },
  'ST13-002': { id: 'ST13-002', name: 'Elmeth', type: 'UNIT', color: 'Green', level: 4, cost: 3, ap: 3, hp: 3, traits: ['Zeon'], link: ['Lalah Sune'], zones: ['Space'],
    text: "【Deploy】Deploy 1 [Bit / Funnel]((Long-Range Weapon)･AP2･HP2･This Unit can't be paired with a Pilot or attack) Unit token.", tip: 'Two bodies for 3. The Funnel blocks nothing but feeds Qubeley and Red Gundam.' },
  'ST13-003': { id: 'ST13-003', name: 'Bertigo', type: 'UNIT', color: 'Green', level: 4, cost: 2, ap: 3, hp: 4, traits: ['SRA'], link: ['Carris Nautilus'], zones: ['Space', 'Earth'], text: '-', tip: "3/4 for 2. I'm a Newtype links it as Carris." },
  'ST13-004': { id: 'ST13-004', name: 'GX-Bit', type: 'UNIT', color: 'Green', level: 2, cost: 2, ap: 3, hp: 1, traits: ['Old UNE', 'Vulture', 'Long-Range Weapon'], zones: ['Space', 'Earth'],
    text: '【Deploy】Look at the top card of your deck. Return it to the top or bottom of your deck.', tip: 'Early 3 AP with a peek at your next draw.' },
  'ST13-005': { id: 'ST13-005', name: 'GFreD', type: 'UNIT', color: 'Green', level: 3, cost: 2, ap: 3, hp: 2, traits: ['Zeon'], zones: ['Space', 'Earth'],
    text: '【Deploy】If 4 or more enemy Units are in play, look at the top 5 cards of your deck. You may reveal 1 Pilot card among them and add it to your hand. Return the remaining cards randomly to the bottom of your deck.', tip: 'Digs for a Pilot when the opponent has gone wide.' },
  'ST13-006': { id: 'ST13-006', name: 'Gundam Aerial', type: 'UNIT', color: 'Red', level: 6, cost: 5, ap: 5, hp: 4, traits: ['Academy'], link: ['Suletta Mercury'], zones: ['Space', 'Earth'],
    text: '【During Pair】【Attack】If you are attacking the enemy player, choose 1 enemy Unit. Deal 2 damage to it.\n【Activate･Action】【Once per Turn】Rest 1 friendly Unit：Choose 1 enemy Unit that is Lv.4 or lower. Deal 1 damage to it.', tip: 'Paired, every attack on the player also deals 2 to a Unit. Rest a Funnel in the action step for 1 more.' },
  'ST13-007': { id: 'ST13-007', name: "Gyunei's Jagd Doga", type: 'UNIT', color: 'Red', level: 4, cost: 3, ap: 3, hp: 4, traits: ['Neo Zeon'], link: ['(Neo Zeon)'], zones: ['Space', 'Earth'],
    text: '【Activate･Main】<Support 1> (Rest this Unit. 1 other friendly Unit gets AP+(specified amount) during this turn.)', keywords: { support: 1 }, tip: 'Support 1 before attacking, or a 3/4 body that Haman links.' },
  'ST13-008': { id: 'ST13-008', name: 'Gundam Throne Zwei', type: 'UNIT', color: 'Red', level: 3, cost: 2, ap: 4, hp: 3, traits: ['CB', 'Trinity'], zones: ['Space', 'Earth'], text: '-', tip: '4 AP for 2 at Lv.3.' },
  'ST13-009': { id: 'ST13-009', name: 'Gundam Pharact', type: 'UNIT', color: 'Red', level: 3, cost: 2, ap: 3, hp: 3, traits: ['Academy'], link: ['(Academy)'], zones: ['Space', 'Earth'],
    text: '【Attack】Choose 1 enemy player. That player chooses 2 Unit cards from their trash. Exile them from the game.', tip: 'Strips recursion targets from their trash every attack.' },
  'ST13-010': { id: 'ST13-010', name: 'Red Gundam (0079)', type: 'UNIT', color: 'Red', level: 5, cost: 4, ap: 4, hp: 4, traits: ['Zeon'], link: ['(Newtype)'], zones: ['Space', 'Earth'],
    text: '【Activate･Main】【Once per Turn】Destroy 1 friendly Unit token：This Unit gains <Breach 3> during this turn.\n(During your turn, when this Unit destroys an enemy Unit with battle damage, deal the specified amount of damage to the first card in that opponent\'s shield area.)', tip: 'Feed it a Funnel: a kill then also hits their shield area for 3.' },
  'ST13-011': { id: 'ST13-011', name: 'Haman Karn', type: 'PILOT', color: 'Green', level: 6, cost: 1, ap: 2, hp: 2, traits: ['Neo Zeon', 'Newtype'],
    text: '【Burst】Add this card to your hand.\n【When Paired】Look at the top 5 cards of your deck. You may reveal 1 Pilot card whose Lv. is equal to or lower than this Unit among them and add it to your hand. Return the remaining cards randomly to the bottom of your deck.', tip: 'Links Qubeley (and triggers its Funnels). Digs for another Pilot.' },
  'ST13-012': { id: 'ST13-012', name: 'Suletta Mercury', type: 'PILOT', color: 'Red', level: 4, cost: 1, ap: 2, hp: 1, traits: ['Academy'],
    text: '【Burst】Add this card to your hand.\n【Once per Turn】When an enemy Unit is destroyed with effect damage while this Unit is attacking, draw 1.', tip: "On Aerial: the Attack trigger's 2 damage kills a Unit, and you draw." },
  'ST13-013': { id: 'ST13-013', name: "I'm a Newtype", type: 'COMMAND', color: 'Green', level: 4, cost: 1, ap: 1, hp: 1, traits: ['SRA', 'Newtype'], timing: ['Main'], pilotName: 'Carris Nautilus',
    text: "【Main】Deploy 1 to 2 [Bit / Funnel]((Long-Range Weapon)･AP2･HP2･This Unit can't be paired with a Pilot or attack) Unit tokens.\n【Pilot】[Carris Nautilus]", tip: 'Two Funnels for 1, or a Newtype Pilot that links Bertigo and Red Gundam.' },
  'ST13-014': { id: 'ST13-014', name: 'Final Duty', type: 'COMMAND', color: 'Red', level: 6, cost: 2, traits: [], timing: ['Main'],
    text: '【Main】Choose 1 of your Units. Destroy it. If you do, look at the top 4 cards of your deck. You may deploy 1 Unit card that is Lv.4 or lower among them. Return the remaining cards randomly to the bottom of your deck.', tip: 'Sacrifice a Funnel to deploy a real Unit from your top 4.' },
  'ST13-015': { id: 'ST13-015', name: 'Operation to Intercept Solomon', type: 'COMMAND', color: 'Red', level: 4, cost: 2, traits: [], timing: ['Main', 'Action'],
    text: '【Burst】Add this card to your hand.\n【Main】/【Action】Choose 3 Unit cards from your trash. Exile them from the game. If you do, choose 1 enemy Unit. Deal 3 damage to it.', tip: '3 damage for 2 Resources once three Units are in your trash.' },
  'ST13-016': { id: 'ST13-016', name: 'Sodon', type: 'BASE', color: 'Green', level: 2, cost: 1, ap: 0, hp: 5, traits: ['Zeon', 'Warship'], zones: ['Space', 'Earth'],
    text: "【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand. Then, deploy 1 [Bit / Funnel]((Long-Range Weapon)･AP2･HP2･This Unit can't be paired with a Pilot or attack) Unit token.", tip: 'A Base, a card, and a Funnel for 1.' },

  // ---------- ST14 Heavy Dominion (White / Green) ----------
  'ST14-001': { id: 'ST14-001', name: 'The-O', type: 'UNIT', color: 'White', level: 9, cost: 8, ap: 6, hp: 7, traits: ['Titans', 'Jupitris'], link: ['Paptimus Scirocco'], zones: ['Space', 'Earth'],
    text: "<Suppression> (Damage to Shields by an attack is dealt to the first 2 cards simultaneously.)\nEach enemy player's rested Units with the lowest Lv. won't be set as active during the start phase of their turn.", keywords: { suppression: true }, tip: 'The biggest Unit in the pool: two Shields per hit, and their smallest attackers stay rested.' },
  'ST14-002': { id: 'ST14-002', name: 'Gundam NT-1 Full Armor', type: 'UNIT', color: 'White', level: 5, cost: 4, ap: 4, hp: 4, traits: ['Earth Federation'], link: ['(Newtype)', 'Christina Mackenzie'], zones: ['Space', 'Earth'],
    text: '<Blocker> (Rest this Unit to change the attack target to it.)', keywords: { blocker: true }, tip: 'A 4/4 Blocker that any Newtype Pilot links.' },
  'ST14-003': { id: 'ST14-003', name: 'Palace Athene', type: 'UNIT', color: 'White', level: 4, cost: 3, ap: 3, hp: 4, traits: ['Titans', 'Jupitris'], link: ['(Jupitris)'], zones: ['Space', 'Earth'],
    text: '【Deploy】Choose 1 enemy player. That player chooses 2 Unit cards from their trash. Exile them from the game.', tip: 'Strips recursion targets; Scirocco links it.' },
  'ST14-004': { id: 'ST14-004', name: 'Geara Doga (Heavy Armed Type)', type: 'UNIT', color: 'White', level: 1, cost: 1, ap: 2, hp: 1, traits: ['Neo Zeon'], zones: ['Space', 'Earth'],
    text: "<Blocker> (Rest this Unit to change the attack target to it.)\nThis Unit can't choose the enemy player as its attack target.", keywords: { blocker: true }, tip: 'A turn-1 Blocker with 2 AP. It can still attack rested Units.' },
  'ST14-005': { id: 'ST14-005', name: 'G-Falcon DX', type: 'UNIT', color: 'White', level: 7, cost: 6, ap: 5, hp: 5, traits: ['Vulture'], link: ['(Vulture)', '(Newtype)'], zones: ['Space', 'Earth'],
    text: '【Deploy】Choose 1 enemy Unit that is Lv.6 or lower. Rest it. Then, if there are 7 or more cards in your trash, it gets AP-2 during this turn.', tip: 'Rests a target on deploy (and shrinks it late), so your other Units can kill it.' },
  'ST14-006': { id: 'ST14-006', name: 'Full Armor Unicorn Gundam (Destroy Mode)', type: 'UNIT', color: 'Green', level: 8, cost: 6, ap: 3, hp: 6, traits: ['Civilian'], link: ['Banagher Links'], zones: ['Space', 'Earth'],
    text: "【Deploy】Look at the top 3 cards of your deck. You may reveal a number of cards equal to the number of enemy players among them and add them to your hand. Return the remaining cards randomly to the bottom of your deck.\n【During Pair】【Once per Turn】When this Unit would receive battle damage from an enemy Unit with AP equal to or less than it, it doesn't receive that damage.", tip: 'Draws on deploy. Paired, it ignores one hit per turn from any Unit with 3 AP or less (5 with Banagher).' },
  'ST14-007': { id: 'ST14-007', name: 'Full Armor Unicorn Gundam (Unicorn Mode)', type: 'UNIT', color: 'Green', level: 5, cost: 3, ap: 4, hp: 4, traits: ['Civilian'], link: ['Banagher Links'], zones: ['Space', 'Earth'],
    text: '<Breach 3> (During your turn, when this Unit destroys an enemy Unit with battle damage, deal the specified amount of damage to the first card in that opponent\'s shield area.)', keywords: { breach: 3 }, tip: '4/4 Breach 3 for 3.' },
  'ST14-008': { id: 'ST14-008', name: 'Gundam Heavyarms Custom (EW)', type: 'UNIT', color: 'Green', level: 6, cost: 4, ap: 6, hp: 4, traits: ['G Team'], link: ['(G Team)', '(Operation Meteor)'], zones: ['Space', 'Earth'], text: '-', tip: '6 AP for 4 kills anything it hits.' },
  'ST14-009': { id: 'ST14-009', name: 'Duel Gundam (Assault Shroud)', type: 'UNIT', color: 'Green', level: 3, cost: 3, ap: 3, hp: 2, traits: ['ZAFT'], link: ['Yzak Jule'], zones: ['Space', 'Earth'],
    text: '【Destroyed】Place 1 EX Resource.', tip: 'Ramps when it dies: trade it early.' },
  'ST14-010': { id: 'ST14-010', name: 'Perfect Strike Gundam', type: 'UNIT', color: 'Green', level: 4, cost: 2, ap: 4, hp: 3, traits: ['Triple Ship Alliance'], link: ['Mu La Flaga'], zones: ['Space', 'Earth'], text: '-', tip: '4/3 for 2.' },
  'ST14-011': { id: 'ST14-011', name: 'Paptimus Scirocco', type: 'PILOT', color: 'White', level: 4, cost: 1, ap: 2, hp: 1, traits: ['Titans', 'Jupitris', 'Newtype'],
    text: '【Burst】Add this card to your hand.\n【Attack】Choose 1 enemy Unit. Reduce its AP during this battle by an amount equal to the number of rested enemy Units.', tip: 'Attack after they have attacked: each rested enemy Unit is -1 AP on your target.' },
  'ST14-012': { id: 'ST14-012', name: 'Banagher Links', type: 'PILOT', color: 'Green', level: 4, cost: 1, ap: 2, hp: 1, traits: ['Civilian', 'Newtype'],
    text: '【Burst】Add this card to your hand.\n【When Paired】Choose 1 friendly Unit that is Lv.5 or higher. During this turn, it may choose an active enemy Unit with 5 or less AP as its attack target.', tip: 'Lets a big Unit attack an active enemy Unit the turn you pair.' },
  'ST14-013': { id: 'ST14-013', name: 'Natural Talent', type: 'COMMAND', color: 'White', level: 4, cost: 2, traits: [], timing: ['Main', 'Action'],
    text: '【Burst】Choose 1 enemy Unit. It gets AP-3 during this turn.\n【Main】/【Action】When playing this card, choose 1 of the following effects and activate it：\n■Choose 1 to 2 enemy Units with 3 or less HP. Rest them.\n■Choose 1 enemy Unit. It gets AP-3 during this turn.', tip: 'Rest two small Units to attack them, or blunt an attacker by 3.' },
  'ST14-014': { id: 'ST14-014', name: 'Blazing Mobile Suit Rider', type: 'COMMAND', color: 'White', level: 5, cost: 1, ap: 2, hp: 1, traits: ['Vulture', 'Newtype'], timing: ['Main', 'Action'], pilotName: 'Garrod Ran & Tiffa Adill',
    text: '【Main】/【Action】Choose 1 enemy Unit that is Lv.5 or lower. It gets AP-3 during this turn. If there are 4 or more Command cards in your trash, choose 1 enemy Unit instead.\n(This card that is being activated is not counted.)\n【Pilot】[Garrod Ran & Tiffa Adill]', tip: 'AP-3 for 1, or a +2 AP Newtype Pilot that links G-Falcon DX and NT-1.' },
  'ST14-015': { id: 'ST14-015', name: 'Battlefield Emotions', type: 'COMMAND', color: 'Green', level: 4, cost: 4, traits: [], timing: ['Main'],
    text: '【Burst】Place 1 EX Resource.\n【Main】Place 1 rested Resource. Then, if you have not set one of your Resources as active with an effect this turn, choose a number of your Resources equal to the number of enemy players. Set them as active.', tip: 'Ramp: a permanent extra Resource, and one of your spent Resources comes back.' },
  'ST14-016': { id: 'ST14-016', name: 'Gryphios 2', type: 'BASE', color: 'White', level: 3, cost: 1, ap: 0, hp: 5, traits: ['Titans', 'Stronghold'], zones: ['Space'],
    text: '【Burst】Deploy this card.\n【Deploy】Add 1 of your Shields to your hand.\n【Once per Turn】During your turn, when a friendly Unit links, choose 1 enemy Unit that is Lv.5 or lower. It gets AP-1 during this turn.', tip: 'Every link shrinks an enemy Unit by 1 for the turn.' },
};

export const TOKENS: Record<string, TokenDef> = {
  'T-001': { id: 'T-001', name: 'Gundam', ap: 3, hp: 3, traits: ['White Base Team'] },
  'T-002': { id: 'T-002', name: 'Guncannon', ap: 2, hp: 2, traits: ['White Base Team'] },
  'T-003': { id: 'T-003', name: 'Guntank', ap: 1, hp: 1, traits: ['White Base Team'] },
  'T-004': { id: 'T-004', name: 'Leo', ap: 1, hp: 1, traits: ['OZ'] },
  'T-005': { id: 'T-005', name: 'Tallgeese', ap: 4, hp: 2, traits: ['OZ'] },
  'T-006': { id: 'T-006', name: "Char's Zaku Ⅱ", ap: 3, hp: 1, traits: ['Zeon'] },
  'T-007': { id: 'T-007', name: 'Zaku Ⅱ', ap: 1, hp: 1, traits: ['Zeon'] },
  'T-008': { id: 'T-008', name: 'Aile Strike Gundam', ap: 3, hp: 3, traits: ['Earth Alliance'], keywords: { blocker: true } },
  'T-009': { id: 'T-009', name: 'Launcher Strike Gundam', ap: 2, hp: 4, traits: ['Earth Alliance'], keywords: { blocker: true } },
  'T-010': { id: 'T-010', name: 'Sword Strike Gundam', ap: 4, hp: 2, traits: ['Earth Alliance'], keywords: { blocker: true } },
  'T-028': { id: 'T-028', name: 'GOOhN', ap: 1, hp: 1, traits: ['ZAFT', 'Marine'] },
  'T-029': { id: 'T-029', name: 'Bit / Funnel', ap: 2, hp: 2, traits: ['Long-Range Weapon'], cantAttack: true, cantPair: true },
  'EX-BASE': { id: 'EX-BASE', name: 'EX Base', ap: 0, hp: 3, traits: [] },
};

export interface DeckDef {
  id: string;
  name: string;
  colors: Color[];
  description: string;
  cards: [string, number][]; // [card id, count]
}

// Starter deck lists. Counts reflect the retail decks (50 cards).
export const DECKS: Record<string, DeckDef> = {
  ST01: {
    id: 'ST01', name: 'Heroic Beginnings', colors: ['Blue', 'White'],
    description: 'Gundam & Aerial. Sturdy units, pilots that link, blockers, and a Base that makes tokens. The best deck to learn on.',
    cards: [
      ['ST01-001', 2], ['ST01-002', 4], ['ST01-003', 4], ['ST01-004', 4], ['ST01-005', 3],
      ['ST01-006', 2], ['ST01-007', 4], ['ST01-008', 3], ['ST01-009', 3],
      ['ST01-010', 4], ['ST01-011', 4],
      ['ST01-012', 3], ['ST01-013', 3], ['ST01-014', 2],
      ['ST01-015', 3], ['ST01-016', 2],
    ],
  },
  ST02: {
    id: 'ST02', name: 'Wings of Advance', colors: ['Green', 'Blue'],
    description: 'Wing Gundam & Tallgeese. Aggressive, ramps with EX Resources, and punishes kills with Breach.',
    cards: [
      ['ST02-001', 2], ['ST02-002', 4], ['ST02-003', 4], ['ST02-004', 4], ['ST02-005', 3],
      ['ST02-006', 2], ['ST02-007', 4], ['ST02-008', 3], ['ST02-009', 3],
      ['ST02-010', 4], ['ST02-011', 4],
      ['ST02-012', 3], ['ST02-013', 3], ['ST02-014', 2],
      ['ST02-015', 3], ['ST02-016', 2],
    ],
  },
  ST03: {
    id: 'ST03', name: "Zeon's Rush", colors: ['Red', 'Green'],
    description: 'Sinanju & Char. Red aggression: Support buffs, direct damage, unblockable attacks; Green bodies that replace themselves.',
    cards: [
      ['ST03-001', 2], ['ST03-002', 4], ['ST03-003', 4], ['ST03-004', 3], ['ST03-005', 3],
      ['ST03-006', 2], ['ST03-007', 3], ['ST03-008', 4], ['ST03-009', 3],
      ['ST03-010', 4], ['ST03-011', 4],
      ['ST03-012', 3], ['ST03-013', 3], ['ST03-014', 2],
      ['ST03-015', 3], ['ST03-016', 3],
    ],
  },
  ST04: {
    id: 'ST04', name: 'SEED Strike', colors: ['White', 'Red'],
    description: 'Strike & Aegis. White disruption: Blockers, bounce, AP reduction; Red sniping with Aegis and First Strike.',
    cards: [
      ['ST04-001', 2], ['ST04-002', 4], ['ST04-003', 4], ['ST04-004', 3], ['ST04-005', 3],
      ['ST04-006', 2], ['ST04-007', 4], ['ST04-008', 3], ['ST04-009', 3],
      ['ST04-010', 4], ['ST04-011', 4],
      ['ST04-012', 3], ['ST04-013', 3], ['ST04-014', 2],
      ['ST04-015', 3], ['ST04-016', 3],
    ],
  },
  ST05: {
    id: 'ST05', name: 'Iron Bloom', colors: ['Purple', 'White'],
    description: 'Barbatos & Tekkadan. Purple self-damage that powers up your Units and Suppression; White Blockers to hold the line.',
    cards: [
      ['ST05-001', 2], ['ST05-002', 4], ['ST05-003', 4], ['ST05-004', 4], ['ST05-005', 4], ['ST05-006', 4],
      ['ST05-007', 2], ['ST05-008', 4], ['ST05-009', 4],
      ['ST05-010', 4], ['ST05-011', 3], ['ST05-012', 3],
      ['ST05-013', 3], ['ST05-014', 2], ['ST01-014', 1],
      ['ST05-015', 2],
    ],
  },
  // Copy counts for ST06-ST14 follow the standard starter distribution (2 LR, 3-4 of other Units, 4 Pilots, 2-3 Commands, 2-3 Bases); exact retail counts were not published in a source I could verify.
  ST06: {
    id: 'ST06', name: 'Clan Unity', colors: ['Red', 'Green'],
    description: 'GQuuuuuuX & Red Gundam. Clan synergy: link triggers, team AP pumps, first strike, and deck peeks.',
    cards: [
      ['ST06-001', 2], ['ST06-002', 4], ['ST06-003', 3], ['ST06-004', 3],
      ['ST06-005', 2], ['ST06-006', 4], ['ST06-007', 3], ['ST06-008', 4],
      ['ST06-009', 4], ['ST06-010', 4],
      ['ST06-011', 3], ['ST06-012', 3], ['ST06-013', 2], ['ST03-013', 3],
      ['ST06-014', 3], ['ST06-015', 3],
    ],
  },
  ST07: {
    id: 'ST07', name: 'Celestial Drive', colors: ['Purple', 'Green'],
    description: 'Celestial Being. Fill the trash with CB cards to power Exia and Setsuna; Dynames and Kyrios hit hard with pilots out.',
    cards: [
      ['ST07-001', 2], ['ST07-002', 4], ['ST07-003', 3], ['ST07-004', 4],
      ['ST07-005', 2], ['ST07-006', 4], ['ST07-007', 3], ['ST07-008', 3],
      ['ST07-009', 4], ['ST07-010', 3], ['ST07-011', 3], ['ST07-012', 3],
      ['ST07-013', 3], ['ST07-014', 3], ['ST05-014', 3],
      ['ST07-015', 3],
    ],
  },
  ST08: {
    id: 'ST08', name: 'Flash of Radiance', colors: ['Red', 'Blue'],
    description: 'Ξ Gundam & Penelope. Red pings and a bomb that gets cheaper as they go wide; Blue card draw with unblockable follow-ups.',
    cards: [
      ['ST08-001', 2], ['ST08-002', 3], ['ST08-003', 4], ['ST08-004', 3], ['ST08-005', 3],
      ['ST08-006', 2], ['ST08-007', 4], ['ST08-008', 3], ['ST08-009', 3],
      ['ST08-010', 4], ['ST08-011', 4],
      ['ST08-012', 3], ['ST08-013', 3], ['ST02-014', 3],
      ['ST08-014', 3], ['ST08-015', 3],
    ],
  },
  // ST09 is an "Ultimate Deck": a 50-card Purple/Red Impulse deck plus 22 extra cards (13 types, incl. Freedom Gundam and White reprints) for customizing. The extras are in the Deck Builder pool.
  ST09: {
    id: 'ST09', name: 'Destiny Ignition', colors: ['Purple', 'Red'],
    description: 'Impulse & Saviour. Purple recursion: Impulse swaps into bigger Impulses from the trash; Red ZAFT snipers finish what survives.',
    cards: [
      ['ST09-001', 4], ['ST09-002', 2], ['ST09-005', 4], ['ST09-006', 4], ['ST09-007', 4],
      ['ST09-003', 2], ['ST04-007', 3], ['GD01-049', 3], ['GD01-054', 3],
      ['ST09-008', 4], ['ST04-011', 4],
      ['ST09-009', 3], ['GD01-111', 3], ['GD02-110', 2],
      ['ST09-010', 3], ['ST04-016', 2],
    ],
  },
  ST10: {
    id: 'ST10', name: 'Generation Pulse', colors: ['Blue', 'White'],
    description: 'Zeta & Barbatos (G Generation). Development: exile cards from your trash to power Deploy and Link effects; Blue draws and rests, White blocks.',
    cards: [
      ['ST10-001', 2], ['ST10-002', 4], ['ST10-003', 3], ['ST10-004', 3], ['ST10-005', 3],
      ['ST10-006', 2], ['ST10-007', 3], ['ST10-008', 4], ['ST10-009', 3], ['ST10-010', 3],
      ['ST10-011', 4], ['ST10-012', 4],
      ['ST10-013', 3], ['ST10-014', 2], ['ST10-015', 3],
      ['ST10-016', 4],
    ],
  },
  ST11: {
    id: 'ST11', name: 'Aquatic Assault', colors: ['Blue', 'Purple'],
    description: "Char's Z'Gok & Shamblo (Marine). Go wide with Marines: untargetable Z'Gok, conditional Blockers, damage reduction, and trash recursion.",
    cards: [
      ['ST11-001', 2], ['ST11-002', 4], ['ST11-003', 3], ['ST11-004', 3], ['ST11-005', 3],
      ['ST11-006', 2], ['ST11-007', 3], ['ST11-008', 4], ['ST11-009', 3], ['ST11-010', 3],
      ['ST11-011', 4], ['ST11-012', 4],
      ['ST11-013', 3], ['ST11-014', 3], ['ST11-015', 2],
      ['ST11-016', 4],
    ],
  },
  ST12: {
    id: 'ST12', name: 'Raging Onslaught', colors: ['Red', 'Purple'],
    description: 'Epyon & Banshee. Close combat: kills that splash damage across the board, First Strike, and a trash that fuels Banshee.',
    cards: [
      ['ST12-001', 2], ['ST12-002', 3], ['ST12-003', 3], ['ST12-004', 3], ['ST12-005', 4],
      ['ST12-006', 2], ['ST12-007', 3], ['ST12-008', 3], ['ST12-009', 3], ['ST12-010', 4],
      ['ST12-011', 4], ['ST12-012', 4],
      ['ST12-013', 2], ['ST12-014', 3], ['ST12-015', 3],
      ['ST12-016', 4],
    ],
  },
  ST13: {
    id: 'ST13', name: 'Silent Barrage', colors: ['Green', 'Red'],
    description: 'Qubeley & Aerial. Bit/Funnel tokens that fight without attacking, effect damage that snowballs, and Pilots that dig for Pilots.',
    cards: [
      ['ST13-001', 2], ['ST13-002', 3], ['ST13-003', 4], ['ST13-004', 3], ['ST13-005', 3],
      ['ST13-006', 2], ['ST13-007', 3], ['ST13-008', 4], ['ST13-009', 3], ['ST13-010', 3],
      ['ST13-011', 4], ['ST13-012', 4],
      ['ST13-013', 3], ['ST13-014', 2], ['ST13-015', 3],
      ['ST13-016', 4],
    ],
  },
  ST14: {
    id: 'ST14', name: 'Heavy Dominion', colors: ['White', 'Green'],
    description: 'The-O & Full Armor Unicorn. Heavy Units: Suppression, damage immunity, AP reduction, ramp into Lv.8-9 bombs.',
    cards: [
      ['ST14-001', 2], ['ST14-002', 3], ['ST14-003', 3], ['ST14-004', 4], ['ST14-005', 2],
      ['ST14-006', 2], ['ST14-007', 3], ['ST14-008', 3], ['ST14-009', 3], ['ST14-010', 4],
      ['ST14-011', 4], ['ST14-012', 4],
      ['ST14-013', 3], ['ST14-014', 3], ['ST14-015', 3],
      ['ST14-016', 4],
    ],
  },
};

export function deckSize(d: DeckDef): number {
  return d.cards.reduce((n, [, c]) => n + c, 0);
}
